// Athar deck v1.6.3 — the public preview must never show the retired Muhammed Khalid card again: EN and AR, 1440x900 and 390x844, in a cache-disabled context
// (CDP Network.setCacheDisabled) the Khalid <video> is the content-hashed 50 s file (duration 50.005 s), the poster is the 18.8 s frame, the card copy carries no
// '0:37' / '00:15.5' (v1.5.5–v1.5.6 copy) / '00:09.1' (v1.6.1 poster); every non-content-addressed document/bundle is Cache-Control: no-store and every /js|/assets
// script/stylesheet tag carries ?v=<version>; served build-info commit == EXPECT_COMMIT (deployed HEAD); the retired Khalid paths answer 404.
// Usage: GUIDE_BASE=https://… EXPECT_COMMIT=<sha> SHOT_PREFIX=after SHOTS_DIR=/path node ../../node_modules/@playwright/test/cli.js test -c playwright.config.mjs
import { test, expect } from '../../node_modules/@playwright/test/index.mjs';
import fs from 'node:fs'; import path from 'node:path'; import crypto from 'node:crypto'; import { execSync } from 'node:child_process';
import { instrument, FILE2CLIP, hashFor } from '../v154/lib.mjs';
const HERE = path.dirname(new URL(import.meta.url).pathname); const BASE = process.env.GUIDE_BASE || 'http://127.0.0.1:4163'; const PREFIX = process.env.SHOT_PREFIX || 'after'; const SHOTS = process.env.SHOTS_DIR || path.join(HERE, 'screenshots');
const RESULTS = path.join(HERE, 'results'); fs.mkdirSync(RESULTS, { recursive: true }); fs.mkdirSync(SHOTS, { recursive: true });
const PKG = JSON.parse(fs.readFileSync(path.join(HERE, '../../package.json'), 'utf8')); const FILMS = JSON.parse(fs.readFileSync(path.join(HERE, '../../features/exec-films/films.json'), 'utf8')); const F = (r) => FILMS.distBase + r; const K = FILMS.films.khalid;
const EXPECT_COMMIT = (process.env.EXPECT_COMMIT || execSync('git rev-parse HEAD', { cwd: HERE }).toString().trim()).toLowerCase(); const NO_CACHE = { 'Cache-Control': 'no-cache', Pragma: 'no-cache' }; const cb = () => '?cb=' + Date.now();
const RETIRED = ['/assets/exec/films/khalid/athar-origins-of-impact-ep01-muhammed-khalid-1080p.mp4', '/assets/exec/films/khalid/athar-origins-of-impact-ep01-muhammed-khalid-720p.mp4', '/assets/exec/films/khalid/athar-origins-of-impact-ep01-poster-09s1.jpg', '/assets/exec/films/khalid/athar-origins-of-impact-ep01.en.vtt', '/assets/exec/films/khalid/athar-origins-of-impact-ep01-muhammed-khalid-poster-18s8.jpg', '/assets/exec/films/khalid/athar-origins-of-impact-ep01-muhammed-khalid.en.vtt', '/assets/exec/video/athar-origins-of-impact-ep01-muhammed-khalid-1080p.mp4', '/assets/exec/video/athar-origins-of-impact-ep01.en.vtt', '/js/exec-film.js'];
const STALE_COPY = ['0:37', '00:15.5', '00:09.1', 'no text-free frame'];
const write = (n, rows) => fs.writeFileSync(path.join(RESULTS, n + '.json'), JSON.stringify({ base: BASE, version: PKG.version, expectCommit: EXPECT_COMMIT, written: new Date().toISOString(), rows }, null, 1));
const vp = (info) => (info.project.name === 'phone' ? '390x844' : '1440x900');
async function setup(page, lang) { await page.addInitScript(instrument(FILE2CLIP, 1)); await page.addInitScript(({ lang }) => { try { sessionStorage.setItem('athar-intro-v1.4.2', 'done'); localStorage.setItem('athar-pact-lang', lang); } catch (e) {} }, { lang }); page.__errors = []; page.__net = []; page.on('pageerror', (e) => page.__errors.push(String(e))); page.on('console', (m) => { if (m.type() === 'error') page.__errors.push(m.text()); }); page.on('requestfailed', (r) => { const f = r.failure(); if (!f || f.errorText !== 'net::ERR_ABORTED') page.__net.push('FAILED ' + (f ? f.errorText : '') + ' ' + r.url()); }); page.on('response', (r) => { if (r.status() >= 400) page.__net.push(r.status() + ' ' + r.url()); }); }
const SEL = '#s-exec-khalid video[data-narration-pause]';

test.describe(`v${PKG.version}`, () => {
  for (const lang of ['en', 'ar']) test(`Khalid card ${lang.toUpperCase()} (cache disabled): hashed 50 s file, 18.8 s poster, current copy, plays`, async ({ page }, info) => {
    test.setTimeout(180000); const mobile = info.project.name === 'phone'; const cdp = await page.context().newCDPSession(page); await cdp.send('Network.enable'); await cdp.send('Network.setCacheDisabled', { cacheDisabled: true }); await setup(page, lang);
    await page.goto(BASE + '/?lang=' + lang + hashFor(43), { waitUntil: 'load' }); await page.waitForFunction(() => !!window.AtharGuide, null, { timeout: 20000 }); await page.waitForFunction(() => window.__qaVisible().n === 43, null, { timeout: 15000 }); await page.waitForTimeout(800);
    const idle = await page.evaluate(async (sel) => { const v = document.querySelector(sel), fig = v.closest('.efp'); await new Promise((r) => { if (v.readyState >= 1) r(); else v.addEventListener('loadedmetadata', r, { once: true }); }); const sw = navigator.serviceWorker ? (await navigator.serviceWorker.getRegistrations()).length : -1; return { lang: document.documentElement.lang, dir: document.documentElement.dir, badge: document.querySelector('[data-testid="deck-version"]').textContent, htmlVersion: document.documentElement.getAttribute('data-deck-version'), src: (v.currentSrc || v.src).split('/').pop(), poster: v.poster.split('/').pop(), posterTime: v.dataset.posterTime, duration: v.duration, dur: fig.querySelector('.efp-dur').textContent, note: fig.querySelector('.efp-note').textContent, title: fig.querySelector('.efp-title').textContent, cardText: document.getElementById('s-exec-khalid').innerText, tracks: [...v.querySelectorAll('track')].map((t) => t.srclang + ':' + t.getAttribute('src').split('/').pop() + (t.default ? ':default' : '')), serviceWorkers: sw, cacheKeys: typeof caches !== 'undefined' ? await caches.keys() : null }; }, SEL);
    await page.screenshot({ path: path.join(SHOTS, `${PREFIX}-card-khalid-${lang}-${vp(info)}.png`) });
    if (mobile) await page.tap('#s-exec-khalid .efp-play'); else await page.click('#s-exec-khalid .efp-play'); await page.waitForFunction((sel) => { const v = document.querySelector(sel); return !v.paused && v.currentTime > 1.0; }, SEL, { timeout: 20000 }); await page.waitForTimeout(300);
    const playing = await page.evaluate((sel) => { const v = document.querySelector(sel); return { paused: v.paused, currentTime: v.currentTime, duration: v.duration, src: (v.currentSrc || v.src).split('/').pop(), showing: [...v.textTracks].filter((t) => t.mode === 'showing').map((t) => t.language + ':' + (t.cues ? t.cues.length : -1)), controls: v.controls }; }, SEL);
    await page.screenshot({ path: path.join(SHOTS, `${PREFIX}-card-khalid-playing-${lang}-${vp(info)}.png`) });
    write(`khalid-${lang}-` + info.project.name, [{ idle, playing, errors: page.__errors, failedRequests: page.__net }]);
    expect(idle.lang).toBe(lang); expect(idle.dir).toBe(lang === 'ar' ? 'rtl' : 'ltr'); expect(idle.badge).toBe('v' + PKG.version); expect(idle.htmlVersion).toBe(PKG.version);
    expect(idle.src).toBe((mobile ? K.mp4Mobile : K.mp4).split('/').pop()); expect(idle.src).toMatch(/khalid-(1080p|720p)\.[0-9a-f]{10}\.mp4$/); expect(Math.abs(idle.duration - 50.005)).toBeLessThan(0.5); expect(idle.poster).toBe(K.poster.split('/').pop()); expect(idle.poster).toMatch(/poster-18s8\.[0-9a-f]{10}\.jpg$/); expect(idle.posterTime).toBe('18.8'); expect(idle.dur).toBe('0:50');
    expect(idle.note).toBe(K.cardNote[lang]); for (const s of STALE_COPY) { expect(idle.cardText, 'stale copy ' + s).not.toContain(s); } expect(idle.tracks).toEqual(['en:' + K.captions.en.split('/').pop() + (lang === 'en' ? ':default' : ''), 'ar:' + K.captions.ar.split('/').pop() + (lang === 'ar' ? ':default' : '')]); expect(idle.serviceWorkers).toBeLessThanOrEqual(0); expect(idle.cacheKeys || []).toEqual([]);
    expect(playing.paused).toBe(false); expect(playing.src).toBe(idle.src); expect(Math.abs(playing.duration - 50.005)).toBeLessThan(0.5); expect(playing.showing).toEqual([lang + ':11']); expect(playing.controls).toBe(true); expect(page.__errors).toEqual([]); expect(page.__net).toEqual([]);
  });
  test('cache policy + deployment identity: no-store on every non-content-addressed file, immutable on hashed files, ?v= on every bundle tag, served build-info commit == deployed HEAD, retired Khalid paths 404', async ({ page }) => {
    test.setTimeout(180000); const rows = [];
    const hdr = async (p) => { const r = await page.request.get(BASE + p + (p.includes('?') ? '&' : '?') + 'cb=' + Date.now(), { headers: NO_CACHE, timeout: 120000 }); const h = r.headers(); const row = { path: p, status: r.status(), cacheControl: h['cache-control'] || null, age: h.age || null, xVercelCache: h['x-vercel-cache'] || null, lastModified: h['last-modified'] || null }; rows.push(row); return { r, row }; };
    for (const p of ['/', '/index.html', '/build-info.json', '/js/exec-films.js', '/js/exec-team.js', '/js/exec-film-player.js', '/js/narration.js', '/assets/exec-team.css', '/assets/exec-film-player.css', '/locales/impact-tiers.en.json', '/locales/impact-tiers.ar.json', '/narration/slide-narration.json', '/narration/narration-manifest.json', '/narration/clip-map.json']) { const { row } = await hdr(p); expect(row.status, p).toBe(200); expect(row.cacheControl, p).toBe('no-store'); }
    for (const p of [F(K.mp4), F(K.captions.en), F(K.captions.ar), F(K.poster)]) { const { row } = await hdr(p); expect(row.status, p).toBe(200); expect(row.cacheControl, p).toContain('immutable'); }
    const html = await (await page.request.get(BASE + '/index.html' + cb(), { headers: NO_CACHE })).text(); const tags = [...html.matchAll(/(?:src|href)="(\/(?:js|assets)\/[^"]+\.(?:js|css)(?:\?[^"]*)?)"/g)].map((m) => m[1]); const unstamped = tags.filter((t) => !/^\/assets\/index-[A-Za-z0-9_-]+\.(js|css)$/.test(t) && !t.endsWith('?v=' + PKG.version)); rows.push({ bundleTags: tags.length, unstamped }); expect(tags.length).toBeGreaterThan(20); expect(unstamped).toEqual([]); expect(html).toContain(`data-deck-version="${PKG.version}"`);
    const vite = tags.filter((t) => /^\/assets\/index-[A-Za-z0-9_-]+\.(js|css)$/.test(t)); for (const p of vite) { const { row } = await hdr(p); expect(row.cacheControl, p).toContain('immutable'); }
    const info = await (await page.request.get(BASE + '/build-info.json' + cb(), { headers: NO_CACHE })).json(); rows.push({ servedCommit: info.commit, expectCommit: EXPECT_COMMIT, servedVersion: info.version, builtAt: info.builtAt, khalid: info.films.find((f) => f.id === 'khalid').file }); expect(info.version).toBe(PKG.version); expect((info.commit || '').toLowerCase()).toBe(EXPECT_COMMIT); expect(info.films.find((f) => f.id === 'khalid').file).toBe(F(K.mp4)); expect(info.films.find((f) => f.id === 'khalid').sha256).toBe(K.mp4Sha256);
    const dl = await page.request.get(BASE + F(K.mp4) + cb(), { headers: NO_CACHE, timeout: 180000 }); const sha = crypto.createHash('sha256').update(await dl.body()).digest('hex'); rows.push({ servedFilm: F(K.mp4), sha256: sha }); expect(sha).toBe(K.mp4Sha256);
    for (const p of RETIRED) { const r = await page.request.get(BASE + p + cb(), { headers: NO_CACHE }); rows.push({ retired: p, status: r.status() }); expect(r.status(), p).toBe(404); }
    const served = await Promise.all(['/js/exec-films.js', '/js/exec-team.js', '/index.html'].map(async (p) => [p, await (await page.request.get(BASE + p + cb(), { headers: NO_CACHE })).text()])); for (const [p, body] of served) for (const s of ['00:15.5', 'no text-free frame', '09s1', 'khalid-1080p.mp4', 'khalid-720p.mp4']) expect(body, p + ' contains ' + s).not.toContain(s);
    write('cache-policy-' + test.info().project.name, rows);
  });
});
