// Athar deck v1.6.4 — fifth Section 09 card: Lorenzo Avitabile (slide 45, #/28/exec-6, after Kayaan Unwalla at the end of the section).
// EN and AR, 1440x900 and 390x844, cache-disabled context: the Lorenzo <video> resolves to the content-hashed 1080p/720p file (duration = the probed 40.000 s ± 0.5),
// the poster is the hashed face-detected frame, EN/AR tracks are present (default follows the language), the card copy carries the decided role line, the film plays;
// Section 09 renders exactly five cards in order (Al Ameri, Ferreira da Cunha, Khalid, Unwalla, Avitabile) and the overview tiles run 40–45; the guide table has an entry + clip for
// slide 45; served build-info commit == EXPECT_COMMIT and version == package version; the other four films are untouched (Khalid 50 s hashed files + 18.8 s poster); every slide EN+AR with
// 0 console errors / 0 failed requests; deep links 32, 38, 39–45 land.
import { test, expect } from '../../node_modules/@playwright/test/index.mjs';
import fs from 'node:fs'; import path from 'node:path'; import crypto from 'node:crypto'; import { execSync } from 'node:child_process';
import { instrument, FILE2CLIP, hashFor } from '../v154/lib.mjs';
const HERE = path.dirname(new URL(import.meta.url).pathname); const BASE = process.env.GUIDE_BASE || 'http://127.0.0.1:4164'; const PREFIX = process.env.SHOT_PREFIX || 'after'; const SHOTS = process.env.SHOTS_DIR || path.join(HERE, 'screenshots');
const RESULTS = path.join(HERE, 'results'); fs.mkdirSync(RESULTS, { recursive: true }); fs.mkdirSync(SHOTS, { recursive: true });
const PKG = JSON.parse(fs.readFileSync(path.join(HERE, '../../package.json'), 'utf8')); const FILMS = JSON.parse(fs.readFileSync(path.join(HERE, '../../features/exec-films/films.json'), 'utf8')); const F = (r) => FILMS.distBase + r; const L = FILMS.films.lorenzo; const K = FILMS.films.khalid;
const TABLE = JSON.parse(fs.readFileSync(path.join(HERE, '../../dist/narration/slide-narration.json'), 'utf8')); const ROW45 = TABLE.slides.find((x) => x.n === 45);
const EXPECT_COMMIT = (process.env.EXPECT_COMMIT || execSync('git rev-parse HEAD', { cwd: HERE }).toString().trim()).toLowerCase(); const NO_CACHE = { 'Cache-Control': 'no-cache', Pragma: 'no-cache' }; const cb = () => '?cb=' + Date.now();
const ORDER = ['s-exec-intro', 's-exec-al-ameri', 's-exec-ferreira-da-cunha', 's-exec-khalid', 's-exec-unwalla', 's-exec-lorenzo'];
const ROLE = { en: 'Senior Advisor — Office of Development Affairs, UAE Presidential Court', ar: 'مستشار أول — مكتب شؤون التنمية، ديوان الرئاسة بدولة الإمارات' }; const NAME = { en: 'Lorenzo Avitabile', ar: 'لورينزو أفيتابيلي' };
const write = (n, rows) => fs.writeFileSync(path.join(RESULTS, n + '.json'), JSON.stringify({ base: BASE, version: PKG.version, expectCommit: EXPECT_COMMIT, written: new Date().toISOString(), rows }, null, 1));
const vp = (info) => (info.project.name === 'phone' ? '390x844' : '1440x900');
async function setup(page, lang) { await page.addInitScript(instrument(FILE2CLIP, 1)); await page.addInitScript(({ lang }) => { try { sessionStorage.setItem('athar-intro-v1.4.2', 'done'); localStorage.setItem('athar-pact-lang', lang); } catch (e) {} }, { lang }); page.__errors = []; page.__net = []; page.on('pageerror', (e) => page.__errors.push(String(e))); page.on('console', (m) => { if (m.type() === 'error') page.__errors.push(m.text()); }); page.on('requestfailed', (r) => { const f = r.failure(); if (!f || f.errorText !== 'net::ERR_ABORTED') page.__net.push('FAILED ' + (f ? f.errorText : '') + ' ' + r.url()); }); page.on('response', (r) => { if (r.status() >= 400) page.__net.push(r.status() + ' ' + r.url()); }); }
async function open(page, n, lang) { await page.goto(BASE + '/' + (lang ? '?lang=' + lang : '') + hashFor(n), { waitUntil: 'load' }); await page.waitForFunction(() => !!window.AtharGuide, null, { timeout: 20000 }); await page.waitForFunction((n) => window.__qaVisible().n === n, n, { timeout: 15000 }); }
const SEL = '#s-exec-lorenzo video[data-narration-pause]';

test.describe(`v${PKG.version}`, () => {
  test('films.json + narration table: lorenzo entry is content-hashed, 40.000 s, poster 14.708 s, EN/AR captions, clip for slide 45; Khalid untouched', async () => {
    expect(PKG.version).toMatch(/^1\.(6\.4|7\.\d+)$/); /* v1.7.0: the v1.6.4 feature set is carried by every later release */ expect(FILMS.version).toBe(PKG.version); expect(Object.keys(FILMS.films)).toEqual(['khalid', 'al-ameri', 'ferreira-da-cunha', 'unwalla', 'lorenzo']); expect(L.status).toBe('shipped');
    for (const [rel, sha] of [[L.mp4, L.mp4Sha256], [L.mp4Mobile, L.mp4MobileSha256], [L.poster, L.posterSha256], [L.posterWebp, L.posterWebpSha256], [L.captions.en, L.captionsSha256.en], [L.captions.ar, L.captionsSha256.ar]]) { expect(rel).toMatch(new RegExp('^lorenzo/lorenzo[-.][^/]*\\.' + sha.slice(0, 10) + '\\.[a-z0-9]+$')); const p = path.join(HERE, '../../features/exec-films/assets', rel); expect(fs.existsSync(p), rel).toBe(true); expect(crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')).toBe(sha); }
    expect(L.mp4).toMatch(/^lorenzo\/lorenzo-1080p\.[0-9a-f]{10}\.mp4$/); expect(L.mp4Mobile).toMatch(/^lorenzo\/lorenzo-720p\.[0-9a-f]{10}\.mp4$/); expect(L.poster).toMatch(/^lorenzo\/lorenzo-poster\.[0-9a-f]{10}\.jpg$/);
    expect(L.durationSec).toBe(40); expect(L.inPt).toBe(0); expect(L.outPt).toBe(40); expect(L.posterTimeSec).toBe(14.708); expect(L.source.sha256).toBe('2040918ea4a042b4f89103454ecdbbaad45bcbc39de0469d0fa7716f3ac2aa07'); expect(L.identity.roleLineOption).toMatch(/^A /); expect(L.identity.confidence).toBe('high');
    const en = fs.readFileSync(path.join(HERE, '../../features/exec-films/assets', L.captions.en), 'utf8'), ar = fs.readFileSync(path.join(HERE, '../../features/exec-films/assets', L.captions.ar), 'utf8'); expect(en.startsWith('WEBVTT')).toBe(true); expect(ar.startsWith('WEBVTT')).toBe(true); expect((en.match(/^c\d\d$/gm) || []).length).toBe(10); expect((ar.match(/^c\d\d$/gm) || []).length).toBe(10);
    expect(ROW45).toBeTruthy(); expect(ROW45.slideId).toBe('s-exec-lorenzo'); expect(ROW45.file).toBe('/audio/guide/slides/NAR-s46-s-exec-lorenzo.mp3'); expect(ROW45.cues).toHaveLength(2); expect(TABLE.slides.map((x) => x.n)).toEqual(Array.from({ length: 48 }, (_, i) => i + 1));
    expect(K.mp4Sha256).toBe('288c67b22bbe38ede92aa4db345c2b0cde7a18d9f3d056d543b4dc1d2e3ac5d1'); expect(K.durationSec).toBe(50); expect(K.posterTimeSec).toBe(18.8); expect(K.mp4).toMatch(/khalid-1080p\.288c67b22b\.mp4$/);
  });
  for (const lang of ['en', 'ar']) test(`Lorenzo card ${lang.toUpperCase()} (cache disabled): fifth and last card, hashed 40 s file, poster, EN/AR tracks, role line, plays; overview tiles 40–45`, async ({ page }, info) => {
    test.setTimeout(180000); const mobile = info.project.name === 'phone'; const cdp = await page.context().newCDPSession(page); await cdp.send('Network.enable'); await cdp.send('Network.setCacheDisabled', { cacheDisabled: true }); await setup(page, lang); await open(page, 45, lang); await page.waitForTimeout(800);
    const idle = await page.evaluate(async (sel) => { const v = document.querySelector(sel), fig = v.closest('.efp'), sec = document.getElementById('s-exec-lorenzo'); await new Promise((r) => { if (v.readyState >= 1) r(); else v.addEventListener('loadedmetadata', r, { once: true }); }); return { lang: document.documentElement.lang, dir: document.documentElement.dir, badge: document.querySelector('[data-testid="deck-version"]').textContent, ids: [...document.querySelectorAll('#root section.ex-slide')].map((x) => x.id), count: window.AtharExecTeam.count, total: window.AtharExecTeam.total, counter: (document.querySelector('footer.pagefooter .counter') || {}).textContent, active: sec.classList.contains('is-active'), n: Number(sec.getAttribute('data-n')), src: (v.currentSrc || v.src).split('/').pop(), poster: v.poster.split('/').pop(), posterTime: v.dataset.posterTime, duration: v.duration, dur: fig.querySelector('.efp-dur').textContent, title: fig.querySelector('.efp-title').textContent, note: (fig.querySelector('.efp-note') || {}).textContent, figDir: fig.getAttribute('dir'), tracks: [...v.querySelectorAll('track')].map((t) => t.srclang + ':' + t.getAttribute('src').split('/').pop() + (t.default ? ':default' : '')), name: (sec.querySelector('.ex-letterhead-name, .ex-name') || {}).textContent, role: (sec.querySelector('.ex-letterhead-role, .ex-role') || {}).textContent, text: sec.innerText, mono: (sec.querySelector('.ex-mono, .ex-roundel') || {}).textContent }; }, SEL);
    await page.screenshot({ path: path.join(SHOTS, `${PREFIX}-card-lorenzo-${lang}-${vp(info)}.png`) });
    if (mobile) await page.tap('#s-exec-lorenzo .efp-play'); else await page.click('#s-exec-lorenzo .efp-play'); await page.waitForFunction((sel) => { const v = document.querySelector(sel); return !v.paused && v.currentTime > 1.0; }, SEL, { timeout: 20000 }); await page.waitForTimeout(300);
    const playing = await page.evaluate((sel) => { const v = document.querySelector(sel); return { paused: v.paused, currentTime: v.currentTime, duration: v.duration, src: (v.currentSrc || v.src).split('/').pop(), showing: [...v.textTracks].filter((t) => t.mode === 'showing').map((t) => t.language + ':' + (t.cues ? t.cues.length : -1)), controls: v.controls, guide: document.getElementById('athar-narration').getAttribute('data-state') }; }, SEL);
    await page.screenshot({ path: path.join(SHOTS, `${PREFIX}-card-lorenzo-playing-${lang}-${vp(info)}.png`) }); await page.evaluate((sel) => document.querySelector(sel).pause(), SEL);
    await page.click('[data-testid="overview-toggle"]'); await page.waitForSelector('[data-testid="overview"] button.ov-card[data-exec]', { timeout: 10000 }); await page.waitForTimeout(500);
    const tiles = await page.evaluate(() => [...document.querySelectorAll('[data-testid="overview"] button.ov-card[data-exec]')].map((b) => b.textContent.trim())); await page.evaluate(() => { const b = document.querySelector('[data-testid="overview"] button.ov-card[data-exec="1"]'); if (b) b.scrollIntoView({ block: 'center' }); }); await page.waitForTimeout(300);
    await page.screenshot({ path: path.join(SHOTS, `${PREFIX}-section09-overview-${lang}-${vp(info)}.png`) });
    write(`lorenzo-${lang}-` + info.project.name, [{ idle: { ...idle, text: undefined }, playing, tiles, errors: page.__errors, failedRequests: page.__net }]);
    expect(idle.lang).toBe(lang); expect(idle.dir).toBe(lang === 'ar' ? 'rtl' : 'ltr'); expect(idle.badge).toBe('v' + PKG.version); expect(idle.ids).toEqual(ORDER); expect(idle.count).toBe(6); expect(idle.total).toBe(48); expect(idle.counter).toContain('45'); expect(idle.active).toBe(true); expect(idle.n).toBe(45);
    expect(idle.src).toBe((mobile ? L.mp4Mobile : L.mp4).split('/').pop()); expect(idle.src).toMatch(/^lorenzo-(1080p|720p)\.[0-9a-f]{10}\.mp4$/); expect(Math.abs(idle.duration - 40.0)).toBeLessThan(0.5); expect(idle.poster).toBe(L.poster.split('/').pop()); expect(idle.posterTime).toBe('14.708'); expect(idle.dur).toBe('0:40'); expect(idle.title).toBe(L.title[lang]); expect(idle.note).toBe(L.cardNote[lang]); expect(idle.figDir).toBe(lang === 'ar' ? 'rtl' : 'ltr');
    expect(idle.tracks).toEqual(['en:' + L.captions.en.split('/').pop() + (lang === 'en' ? ':default' : ''), 'ar:' + L.captions.ar.split('/').pop() + (lang === 'ar' ? ':default' : '')]);
    expect(idle.text).toContain(NAME[lang]); expect(idle.text).toContain(ROLE[lang]); expect(idle.text).not.toMatch(/Surname and role awaiting confirmation|بانتظار تأكيد اسم العائلة/);
    expect(playing.paused).toBe(false); expect(playing.src).toBe(idle.src); expect(playing.showing).toEqual([lang + ':10']); expect(playing.controls).toBe(true);
    expect(tiles).toHaveLength(6); expect(tiles[0]).toMatch(/^40/); expect(tiles[5]).toMatch(/^45/); expect(tiles[5]).toContain(NAME[lang]); expect(tiles[4]).toMatch(/^44/);
    expect(page.__errors).toEqual([]); expect(page.__net).toEqual([]);
  });
  test('served files: Lorenzo 1080p/720p/poster/VTT + guide clip 200 with matching sha256 (immutable for hashed files), served build-info commit == deployed HEAD and lists lorenzo, served exec-team.js has the real card and no placeholder, "Five letters" lede', async ({ page }) => {
    test.setTimeout(300000); const rows = [];
    for (const [key, rel, sha] of [['mp4', L.mp4, L.mp4Sha256], ['mp4Mobile', L.mp4Mobile, L.mp4MobileSha256], ['poster', L.poster, L.posterSha256], ['posterWebp', L.posterWebp, L.posterWebpSha256], ['vttEn', L.captions.en, L.captionsSha256.en], ['vttAr', L.captions.ar, L.captionsSha256.ar]]) { const r = await page.request.get(BASE + F(rel) + cb(), { headers: NO_CACHE, timeout: 180000 }); const body = await r.body(); const got = crypto.createHash('sha256').update(body).digest('hex'); const cc = r.headers()['cache-control'] || ''; rows.push({ key, url: F(rel), status: r.status(), bytes: body.length, sha256: got, cacheControl: cc }); expect(r.status(), key).toBe(200); expect(got, key).toBe(sha); expect(cc, key).toContain('immutable'); }
    const clip = await page.request.get(BASE + ROW45.file + cb(), { headers: NO_CACHE }); const cbody = await clip.body(); rows.push({ clip: ROW45.file, status: clip.status(), bytes: cbody.length, sha256: crypto.createHash('sha256').update(cbody).digest('hex') }); expect(clip.status()).toBe(200); expect(crypto.createHash('sha256').update(cbody).digest('hex')).toBe(ROW45.sha256); expect(cbody.length).toBe(ROW45.bytes);
    const info = await (await page.request.get(BASE + '/build-info.json' + cb(), { headers: NO_CACHE })).json(); const lf = info.films.find((f) => f.id === 'lorenzo'); rows.push({ servedCommit: info.commit, expectCommit: EXPECT_COMMIT, servedVersion: info.version, builtAt: info.builtAt, lorenzo: lf }); expect(info.version).toBe(PKG.version); expect((info.commit || '').toLowerCase()).toBe(EXPECT_COMMIT); expect(lf).toBeTruthy(); expect(lf.status).toBe('shipped'); expect(lf.file).toBe(F(L.mp4)); expect(lf.sha256).toBe(L.mp4Sha256); expect(lf.durationSec).toBe(40); expect(info.films.find((f) => f.id === 'khalid').sha256).toBe(K.mp4Sha256);
    const et = await (await page.request.get(BASE + '/js/exec-team.js' + cb(), { headers: NO_CACHE })).text(); expect(et).toContain("id: 'lorenzo'"); expect(et).toContain(ROLE.en); expect(et).toContain(ROLE.ar); expect(et).not.toContain('Surname and role awaiting confirmation'); expect(et).toContain('Five letters of introduction'); expect(et).toContain('خمس رسائل تعريف');
    const ef = await (await page.request.get(BASE + '/js/exec-films.js' + cb(), { headers: NO_CACHE })).text(); for (const rel of [L.mp4, L.mp4Mobile, L.poster, L.captions.en, L.captions.ar]) expect(ef).toContain(F(rel));
    const sums = fs.readFileSync(path.join(HERE, '../../SHA256SUMS.txt'), 'utf8'); for (const [rel, sha] of [[L.mp4, L.mp4Sha256], [L.mp4Mobile, L.mp4MobileSha256], [L.poster, L.posterSha256]]) expect(sums).toContain(sha + '  ./dist' + F(rel)); expect(sums).toContain(ROW45.sha256 + '  ./dist' + ROW45.file);
    write('served-' + test.info().project.name, rows);
  });
  test('deep links 32, 38, 39–45 and all 45 slides EN + AR with 0 console errors and 0 failed requests; RTL in AR', async ({ page }) => {
    test.setTimeout(300000); await setup(page, 'en'); await open(page, 1); const dirs = {};
    for (const lang of ['en', 'ar']) { if (lang === 'ar') { await page.click('[data-testid="lang-toggle"]'); await page.waitForFunction(() => document.documentElement.dir === 'rtl', null, { timeout: 8000 }); } for (let n = 1; n <= 48; n++) { await page.evaluate((h) => { location.hash = h; }, hashFor(n)); await page.waitForFunction((n) => window.__qaVisible().n === n, n, { timeout: 9000 }); } dirs[lang] = await page.evaluate(() => document.documentElement.dir); }
    const deep = [];
    for (const lang of ['en', 'ar']) for (const n of [32, 38, 39, 40, 41, 42, 43, 44, 45]) { const ctx = await page.context().browser().newContext({ viewport: page.viewportSize() }); const p2 = await ctx.newPage(); await setup(p2, lang); await p2.goto(BASE + '/?lang=' + lang + hashFor(n), { waitUntil: 'load' }); await p2.waitForFunction(() => !!window.AtharGuide, null, { timeout: 20000 }); await p2.waitForFunction((n) => window.__qaVisible().n === n, n, { timeout: 15000 }); const got = await p2.evaluate(() => ({ n: window.__qaVisible().n, id: window.__qaVisible().id || null, dir: document.documentElement.dir })); deep.push({ lang, n, hash: hashFor(n), ...got, errors: p2.__errors.length, failed: p2.__net.length }); expect(got.n, lang + ' ' + hashFor(n)).toBe(n); expect(p2.__errors, 'deep link ' + n).toEqual([]); expect(p2.__net, 'deep link ' + n).toEqual([]); await ctx.close(); }
    write('sweep-' + test.info().project.name, [{ dirs, errors: page.__errors, failedRequests: page.__net, deep }]); expect(dirs).toEqual({ en: 'ltr', ar: 'rtl' }); expect(page.__errors).toEqual([]); expect(page.__net).toEqual([]);
  });
});
