// Athar deck v1.6.2 — the ~50 s Muhammed Khalid executive film installed (replaces the 37.333 s trim); every other check is a regression guard.
// Usage: GUIDE_BASE=http://127.0.0.1:4162 SHOT_PREFIX=after SHOTS_DIR=/path npx playwright test -c qa/v162/playwright.config.mjs
import { test, expect } from '../../node_modules/@playwright/test/index.mjs';
import fs from 'node:fs'; import path from 'node:path'; import crypto from 'node:crypto';
import { instrument, FILE2CLIP, hashFor } from '../v154/lib.mjs';
const HERE = path.dirname(new URL(import.meta.url).pathname); const BASE = process.env.GUIDE_BASE || 'http://127.0.0.1:4162'; const PREFIX = process.env.SHOT_PREFIX || 'after'; const SHOTS = process.env.SHOTS_DIR || path.join(HERE, 'screenshots');
const RESULTS = path.join(HERE, 'results'); fs.mkdirSync(RESULTS, { recursive: true }); fs.mkdirSync(SHOTS, { recursive: true });
const PKG = JSON.parse(fs.readFileSync(path.join(HERE, '../../package.json'), 'utf8')); const FILMS = JSON.parse(fs.readFileSync(path.join(HERE, '../../features/exec-films/films.json'), 'utf8')); const F = (r) => FILMS.distBase + r;
const SUMS = Object.fromEntries(fs.readFileSync(path.join(HERE, '../../SHA256SUMS.txt'), 'utf8').trim().split('\n').map((l) => { const m = /^([0-9a-f]{64}) [ *]\.\/dist(\/.+)$/.exec(l.trim()); return m ? [m[2], m[1]] : null; }).filter(Boolean));
const CLIPS = JSON.parse(fs.readFileSync(path.join(HERE, '../../dist/narration/clip-map.json'), 'utf8')); const SLIDES = JSON.parse(fs.readFileSync(path.join(HERE, '../../dist/narration/slide-narration.json'), 'utf8')); const MANIFEST = JSON.parse(fs.readFileSync(path.join(HERE, '../../dist/narration/narration-manifest.json'), 'utf8'));
const K = FILMS.films.khalid; const CARDS = [['al-ameri', 2, 41], ['ferreira-da-cunha', 3, 42], ['khalid', 4, 43], ['unwalla', 5, 44]];
const write = (n, rows) => fs.writeFileSync(path.join(RESULTS, n + '.json'), JSON.stringify({ base: BASE, version: PKG.version, written: new Date().toISOString(), rows }, null, 1));
const vp = (info) => (info.project.name === 'phone' ? '390x844' : '1440x900'); const shot = (page, info, name) => page.screenshot({ path: path.join(SHOTS, `${PREFIX}-${name}-${vp(info)}.png`) });
async function setup(page, lang = 'en') { await page.addInitScript(instrument(FILE2CLIP, 1)); await page.addInitScript(({ lang }) => { try { sessionStorage.setItem('athar-intro-v1.4.2', 'done'); localStorage.setItem('athar-pact-lang', lang); } catch (e) {} }, { lang }); page.__errors = []; page.on('pageerror', (e) => page.__errors.push(String(e))); page.on('console', (m) => { if (m.type() === 'error') page.__errors.push(m.text()); }); }
async function open(page, n, lang) { await page.goto(BASE + '/' + (lang ? '?lang=' + lang : '') + hashFor(n), { waitUntil: 'load' }); await page.waitForFunction(() => !!window.AtharGuide, null, { timeout: 20000 }); await page.waitForFunction((n) => window.__qaVisible().n === n, n, { timeout: 15000 }); }
const waitState = (page, src, ms = 10000) => page.waitForFunction((src) => { const r = document.getElementById('athar-narration'); const s = { state: r.getAttribute('data-state'), reason: r.getAttribute('data-reason') }; return new Function('s', 'return ' + src)(s); }, src, { timeout: ms });
const SEL = '#s-exec-khalid video[data-narration-pause]';

test.describe(`v${PKG.version}`, () => {
  test('films.json: Khalid is the 50 s cut (not the 40.000 s master nor the 37.333 s trim); version 1.6.2 everywhere', async ({ page }) => {
    expect(PKG.version).toBe('1.6.2'); expect(FILMS.version).toBe('1.6.2'); expect(K.status).toBe('shipped'); expect(K.durationSec).toBeGreaterThan(45); expect(K.durationSec).toBeLessThan(55); expect(K.deliveredDurationSec).toBe(K.installedDurationSec); expect(K.outPt).toBe(K.durationSec); expect(K.durationLabel).toBe('0:50');
    expect(K.source.sha256).not.toMatch(/^c7c20005/); expect(K.mp4Sha256).not.toBe('f71b761b455fd329eb96d66de2c9bbf48bb6e69ab90a904b8146397f33ad6048'); expect(K.poster).toContain('poster-18s8'); expect(K.posterTimeSec).toBe(18.8); expect(K.cardNote.en).toContain('00:18.8'); expect(K.cardNote.ar).toContain('00:18.8');
    const retired = Object.keys(SUMS).filter((p) => /khalid/.test(p) && /(09s1|ep01\.(en|ar)\.vtt|f71b761b)/.test(p)); expect(retired).toEqual([]);
    await setup(page); await open(page, 43); const v = await page.evaluate(() => ({ badge: document.querySelector('[data-testid="deck-version"]').textContent, html: document.documentElement.getAttribute('data-deck-version'), exec: window.AtharExecTeam.version, films: window.AtharExecFilms.version, player: window.AtharExecFilmPlayer.version, guide: window.AtharGuide.version, note: document.querySelector('#s-exec-khalid .efp-note').textContent, dur: document.querySelector('#s-exec-khalid .efp-dur').textContent }));
    const info = await (await page.request.get(BASE + '/build-info.json')).json(); write('version-' + test.info().project.name, [{ ...v, buildInfo: info.version, films: info.films.map((f) => f.id + ':' + f.status + ':' + f.sha256.slice(0, 8)) }]);
    expect(v.badge).toBe('v1.6.2'); expect(v.html).toBe('1.6.2'); expect(v.exec).toBe('v1.6.2'); expect(v.films).toBe('1.6.2'); expect(v.player).toBe('v1.6.2'); expect(v.guide).toBe('v1.6.2'); expect(info.version).toBe('1.6.2'); expect(info.features.version).toBe('1.6.2'); expect(info.films.find((f) => f.id === 'khalid').sha256).toBe(K.mp4Sha256);
    expect(v.note).toBe(K.cardNote.en); expect(v.dur).toBe('0:50'); expect(page.__errors).toEqual([]);
  });
  test('Khalid card: poster shows, no autoplay after 5 s, play → native controls, guide pauses / resumes on pause and after the end, duration ≈ 50 s', async ({ page }, info) => {
    test.setTimeout(240000); const mobile = info.project.name === 'phone'; await setup(page); await open(page, 43);
    if (mobile) await page.tap('[data-testid="guide-toggle"]'); else await page.click('[data-testid="guide-toggle"]'); await waitState(page, "s.state === 'playing' || s.state === 'loading' || s.state === 'ended'", 15000);
    await page.waitForTimeout(5000);
    const idle = await page.evaluate(async (sel) => { const v = document.querySelector(sel), fig = v.closest('.efp'); await new Promise((r) => { if (v.readyState >= 1) r(); else v.addEventListener('loadedmetadata', r, { once: true }); }); const im = new Image(); const posterLoaded = await new Promise((r) => { im.onload = () => r(im.naturalWidth > 0); im.onerror = () => r(false); im.src = v.poster; }); return { poster: v.poster.split('/').pop(), posterLoaded, posterVisible: getComputedStyle(v).visibility !== 'hidden' && v.getBoundingClientRect().width > 100, paused: v.paused, currentTime: v.currentTime, autoplay: v.hasAttribute('autoplay'), readyState: v.readyState, duration: v.duration, controls: v.controls, overlay: getComputedStyle(fig.querySelector('.efp-play')).display !== 'none', src: (v.currentSrc || '').split('/').pop(), variant: v.getAttribute('data-efp-variant'), tracks: [...v.querySelectorAll('track')].map((t) => t.srclang + ':' + t.getAttribute('src').split('/').pop() + (t.default ? ':default' : '')) }; }, SEL);
    expect(idle.poster).toBe(K.poster.split('/').pop()); expect(idle.posterLoaded).toBe(true); expect(idle.posterVisible).toBe(true); expect(idle.paused).toBe(true); expect(idle.currentTime).toBe(0); expect(idle.autoplay).toBe(false); expect(idle.overlay).toBe(true); expect(Math.abs(idle.duration - K.durationSec)).toBeLessThan(0.2); expect(idle.src).toBe((mobile ? K.mp4Mobile : K.mp4).split('/').pop()); expect(idle.tracks).toEqual(['en:' + K.captions.en.split('/').pop() + ':default', 'ar:' + K.captions.ar.split('/').pop()]);
    await shot(page, info, 'card-khalid-idle-en');
    const g0 = await page.evaluate(() => document.getElementById('athar-narration').getAttribute('data-state'));
    if (mobile) await page.tap('#s-exec-khalid .efp-play'); else await page.click('#s-exec-khalid .efp-play'); await page.waitForFunction((sel) => { const v = document.querySelector(sel); return !v.paused && v.currentTime > 0.6; }, SEL, { timeout: 15000 }); await waitState(page, "s.state === 'paused' && s.reason === 'video'", 8000); await page.waitForTimeout(500);
    const playing = await page.evaluate((sel) => { const v = document.querySelector(sel), fig = v.closest('.efp'); return { controls: v.controls, overlayHidden: getComputedStyle(fig.querySelector('.efp-play')).display === 'none', showing: [...v.textTracks].filter((t) => t.mode === 'showing').map((t) => t.language), readyState: v.readyState, duration: v.duration, currentTime: v.currentTime, guide: document.getElementById('athar-narration').getAttribute('data-state') }; }, SEL);
    await shot(page, info, 'card-khalid-playing-en'); expect(playing.controls).toBe(true); expect(playing.overlayHidden).toBe(true); expect(playing.showing).toEqual(['en']); expect(playing.guide).toBe('paused');
    await page.evaluate((sel) => document.querySelector(sel).pause(), SEL); await waitState(page, "s.state === 'playing' || s.state === 'loading'", 10000); const gPause = await page.evaluate(() => document.getElementById('athar-narration').getAttribute('data-state'));
    await page.evaluate(async (sel) => { const v = document.querySelector(sel); v.currentTime = v.duration - 2.5; await v.play(); }, SEL); await waitState(page, "s.state === 'paused' && s.reason === 'video'", 8000);
    await page.waitForFunction((sel) => { const v = document.querySelector(sel); return v.paused && v.currentTime >= v.duration - 0.3; }, SEL, { timeout: 15000 }); await waitState(page, "s.state === 'playing' || s.state === 'loading' || s.state === 'ended'", 10000);
    const end = await page.evaluate((sel) => { const v = document.querySelector(sel), fig = v.closest('.efp'); return { ended: v.ended || v.paused, currentTime: v.currentTime, duration: v.duration, replay: fig.querySelector('.efp-play').textContent, guide: document.getElementById('athar-narration').getAttribute('data-state') }; }, SEL);
    write('khalid-player-' + info.project.name, [{ idle, playing, gPause, end, guide0: g0, errors: page.__errors.slice() }]); expect(end.ended).toBe(true); expect(['playing', 'loading', 'ended']).toContain(end.guide); expect(['playing', 'loading']).toContain(gPause); expect(page.__errors).toEqual([]);
  });
  test('Khalid captions: EN and AR tracks load (cues parsed) and the showing track follows the language toggle; RTL in AR', async ({ page }, info) => {
    test.setTimeout(120000); await setup(page); await open(page, 43);
    const en = await page.evaluate(async (sel) => { const v = document.querySelector(sel); for (const t of v.textTracks) t.mode = t.language === 'en' ? 'showing' : 'hidden'; await new Promise((r) => setTimeout(r, 1500)); return { cues: [...v.textTracks].map((t) => t.language + ':' + (t.cues ? t.cues.length : -1)), showing: [...v.textTracks].filter((t) => t.mode === 'showing').map((t) => t.language), dir: document.documentElement.dir, fig: v.closest('.efp').getAttribute('dir') }; }, SEL);
    await page.click('[data-testid="lang-toggle"]'); await page.waitForFunction(() => document.documentElement.lang === 'ar' && document.querySelector('#s-exec-khalid .efp[dir="rtl"]'), null, { timeout: 10000 }); await page.waitForTimeout(800);
    const ar = await page.evaluate((sel) => { const v = document.querySelector(sel), fig = v.closest('.efp'); return { defaultTrack: ([...v.querySelectorAll('track')].find((t) => t.default) || {}).srclang, dir: document.documentElement.dir, fig: fig.getAttribute('dir'), lang: fig.getAttribute('lang'), title: fig.querySelector('.efp-title').textContent, note: fig.querySelector('.efp-note').textContent, cc: fig.querySelector('.efp-cc').textContent }; }, SEL);
    await shot(page, info, 'card-khalid-ar'); write('khalid-captions-' + info.project.name, [{ en, ar }]);
    expect(en.cues).toEqual(['en:11', 'ar:11']); expect(en.showing).toEqual(['en']); expect(en.dir).toBe('ltr'); expect(ar.dir).toBe('rtl'); expect(ar.fig).toBe('rtl'); expect(ar.lang).toBe('ar'); expect(ar.defaultTrack).toBe('ar'); expect(ar.title).toBe(K.title.ar); expect(ar.note).toBe(K.cardNote.ar); expect(page.__errors).toEqual([]);
  });
  for (const [who, k, n] of CARDS) test(`${who}: film plays through the shared player (regression)`, async ({ page }, info) => {
    test.setTimeout(120000); const mobile = info.project.name === 'phone'; const f = FILMS.films[who]; const sel = `#s-exec-${who} video[data-narration-pause]`; await setup(page); await open(page, n);
    if (mobile) await page.tap(`#s-exec-${who} .efp-play`); else await page.click(`#s-exec-${who} .efp-play`); await page.waitForFunction((sel) => { const v = document.querySelector(sel); return !v.paused && v.currentTime > 0.6; }, sel, { timeout: 15000 });
    const r = await page.evaluate((sel) => { const v = document.querySelector(sel); return { duration: v.duration, controls: v.controls, readyState: v.readyState, t: v.currentTime }; }, sel); write(`film-${who}-` + info.project.name, [{ ...r, filmsJson: f.durationSec }]); expect(Math.abs(r.duration - f.durationSec)).toBeLessThan(0.2); expect(r.controls).toBe(true); expect(page.__errors).toEqual([]);
  });
  test('HTTP 200 + sha256 of every film variant, poster and VTT against films.json and SHA256SUMS; 55/55 narration clips 200', async ({ page }) => {
    test.setTimeout(600000); const rows = [];
    for (const [id, f] of Object.entries(FILMS.films)) { if (f.status !== 'shipped') continue; for (const [key, rel, want] of [['mp4', f.mp4, f.mp4Sha256], ['mp4Mobile', f.mp4Mobile, f.mp4MobileSha256], ['poster', f.poster, f.posterSha256], ['posterWebp', f.posterWebp, f.posterWebpSha256 || null], ['vttEn', f.captions.en, f.captionsSha256.en], ['vttAr', f.captions.ar, f.captionsSha256.ar]]) { if (!rel) continue; const u = F(rel); const r = await page.request.get(BASE + u, { timeout: 180000 }); const body = await r.body(); const sha = crypto.createHash('sha256').update(body).digest('hex'); rows.push({ id, key, url: u, status: r.status(), bytes: body.length, sha256: sha, filmsJson: want, sums: SUMS[u] }); expect(r.status(), u).toBe(200); if (want) expect(sha, u + ' vs films.json').toBe(want); expect(sha, u + ' vs SHA256SUMS').toBe(SUMS[u]); } }
    const clips = [...new Set([...CLIPS.clips.map((c) => c.file), ...SLIDES.slides.map((x) => x.file), ...MANIFEST.segments.map((x) => x.audio).filter(Boolean)])]; /* 10 section guides + 44 slide clips + the intro narration = 55 */ let ok = 0; for (const c of clips) { const r = await page.request.get(BASE + c, { timeout: 60000 }); if (r.status() === 200) ok++; else rows.push({ clip: c, status: r.status() }); }
    write('assets-' + test.info().project.name, [{ clips: clips.length, clipsOk: ok }, ...rows]); expect(clips.length).toBe(55); expect(ok).toBe(55);
  });
  test('deep links 32, 38, 39–44 and all 44 slides EN + AR with 0 console errors; RTL in AR', async ({ page }) => {
    test.setTimeout(300000); await setup(page); await open(page, 1); const dirs = {};
    for (const lang of ['en', 'ar']) { if (lang === 'ar') { await page.click('[data-testid="lang-toggle"]'); await page.waitForFunction(() => document.documentElement.dir === 'rtl', null, { timeout: 8000 }); } for (let n = 1; n <= 44; n++) { await page.evaluate((h) => { location.hash = h; }, hashFor(n)); await page.waitForFunction((n) => window.__qaVisible().n === n, n, { timeout: 9000 }); } dirs[lang] = await page.evaluate(() => document.documentElement.dir); }
    for (const n of [32, 38, 39, 40, 41, 42, 43, 44]) { const ctx = await page.context().browser().newContext({ viewport: page.viewportSize() }); const p2 = await ctx.newPage(); await setup(p2); await p2.goto(BASE + '/' + hashFor(n), { waitUntil: 'load' }); await p2.waitForFunction(() => !!window.AtharGuide, null, { timeout: 20000 }); await p2.waitForFunction((n) => window.__qaVisible().n === n, n, { timeout: 15000 }); expect(p2.__errors, 'deep link ' + n).toEqual([]); await ctx.close(); }
    write('sweep-' + test.info().project.name, [{ dirs, errors: page.__errors }]); expect(dirs).toEqual({ en: 'ltr', ar: 'rtl' }); expect(page.__errors).toEqual([]);
  });
});
