// Athar deck v1.7.3 — audit-fix suite for Section 10 "Brand" (46 Brand foundations · 47 Typography · 48 Product & asset gallery). One test per applied
// finding of qa/audit-v172.json, measured in the browser (cache disabled, fresh context per test, 1440x900 + 390x844, EN + AR):
//  (1) release metadata (node): every version literal == package.json; slide 47 narration row = NAR-s52 EN + AR (files, sha256, duration, Scribe content check,
//      cues anchored s47-*); NAR-s47 gone; the render-laptop-phone-dashboard set = 3 content-hashed files derived from the EDITED render (sourceSha256 46a9f701…)
//      with a PINNED monogram composite (kind monogram, h ≥ 32 px, opacity 1) — the recomposite script re-derives the hashes when the inputs are available
//      (V173_RENDER / V173_LOGO env); brand.json secondaryRow citation (Table 3.1); SHA256SUMS; no service worker; CHANGELOG / RELEASE_NOTES / ledger; no HEX literal;
//  (2) slides 46–48 × EN/AR: A-01 scroll region (tabindex=0 · role=region · aria-label · visible ≥3 px focus ring); measured WCAG text contrast ≥ 4.5:1 (≥ 3:1 large)
//      for EVERY visible text node; axe-core 0 violations (0 critical / serious required, 0 overall measured); A-06 AR kicker letter-spacing 0; A-10 table headers;
//      A-12 core row == token file (5) + labelled secondary row == palette Emerald/Sand (2, heading cites Table 3.1); A-13 46 / 48 fit at 1440x900; 47 clip NAR-s52
//      resolved AND audible after pressing N (EN + AR); 48: 11 tiles div[role=group][aria-labelledby] with a real <button> ≥ 44x44 named "Enlarge: <caption>",
//      width-descriptor WebP srcsets + sizes + JPEG fallback, the laptop tile serves the NEW hashes, no horizontal caption overflow; lightbox (keyboard): role=dialog,
//      aria-modal, aria-labelledby → caption text, Close ≥ 44x44, Tab/Shift+Tab stay inside, Esc closes, focus returns to the button, overview NOT opened, hash #/29/brand-3;
//      RTL: swatch rows and tiles mirrored, Close on the inline-end side; footer v<version>, counter 'n of 48', 0 console errors / 0 failed requests; screenshots;
//  (3) served + routes: build-info version/commit; new audio + laptop files 200 + sha256 (+ immutable), retired files 404; #/29/brand-k, #/28/brand-k and
//      #slide-46…48 land AND the address bar keeps #/29/brand-k; deep links 32 / 38 / 39–45 unchanged; runtime hash set from slide 12; reload on #/29/brand-2;
//      keyboard 45 → 46 → 45; 19 article links not re-checked here (qa/v161 / release report).
// Usage: GUIDE_BASE=https://host EXPECT_COMMIT=<sha> SHOT_PREFIX=after SHOTS_DIR=/path PW_WORKERS=2 node ../../node_modules/@playwright/test/cli.js test -c playwright.config.mjs
import { test, expect } from '../../node_modules/@playwright/test/index.mjs';
import fs from 'node:fs'; import path from 'node:path'; import crypto from 'node:crypto'; import { execSync, spawnSync } from 'node:child_process';
import { instrument, FILE2CLIP, hashFor } from '../v154/lib.mjs';
const HERE = path.dirname(new URL(import.meta.url).pathname); const ROOT = path.join(HERE, '../..'); const BASE = process.env.GUIDE_BASE || 'http://127.0.0.1:4173'; const PREFIX = process.env.SHOT_PREFIX || 'after'; const SHOTS = process.env.SHOTS_DIR || path.join(HERE, 'screenshots');
const RESULTS = path.join(HERE, 'results'); fs.mkdirSync(RESULTS, { recursive: true }); fs.mkdirSync(SHOTS, { recursive: true });
const read = (rel) => fs.readFileSync(path.join(ROOT, rel), 'utf8'); const sha256 = (buf) => crypto.createHash('sha256').update(buf).digest('hex');
const PKG = JSON.parse(read('package.json')); const V = PKG.version; const BRAND = JSON.parse(read('features/brand/brand.json')); const TOK = JSON.parse(read('features/brand/brand-tokens.json')); const ASSETS = JSON.parse(read('features/brand/assets.json'));
const TABLE = JSON.parse(read('dist/narration/slide-narration.json')); const MANIFEST = JSON.parse(read('dist/narration/narration-manifest.json'));
const EXPECT_COMMIT = (process.env.EXPECT_COMMIT || execSync('git rev-parse HEAD', { cwd: HERE }).toString().trim()).toLowerCase(); const NO_CACHE = { 'Cache-Control': 'no-cache', Pragma: 'no-cache' }; const cb = () => '?cb=' + Date.now();
const SLIDES = [[46, 's-brand-foundations', 1, 'NAR-s50'], [47, 's-brand-typography', 2, 'NAR-s52'], [48, 's-brand-gallery', 3, 'NAR-s51']];
const byName = (arr, n) => { const h = arr.find((t) => t.name === n); if (!h) throw new Error('token missing: ' + n); return h.hex; };
const TOKEN_HEX = BRAND.colourSystem.tokens.map((t) => byName(TOK.superseded, t.token)); const ACCENT_HEX = BRAND.colourSystem.accents.map((a) => byName(TOK.palette, a.name));
const LAPTOP = ASSETS.items.filter((i) => i.setId === 'render-laptop-phone-dashboard'); const LAPTOP_SRC_SHA = '46a9f70191cade82ebb48d37cdc057a118b883379b3509a9eec8b673dc79e9f6';
const OLD_LAPTOP = ['gallery/render-laptop-phone-dashboard@2x.51124ee7e9.webp', 'gallery/render-laptop-phone-dashboard@1x.296284b693.webp', 'gallery/render-laptop-phone-dashboard.84b9679ee2.jpg'];
const AXE = fs.readFileSync(path.join(ROOT, 'qa/v173/axe.min.js'), 'utf8');
const write = (n, rows) => fs.writeFileSync(path.join(RESULTS, n + '.json'), JSON.stringify({ base: BASE, version: V, expectCommit: EXPECT_COMMIT, written: new Date().toISOString(), rows }, null, 1));
const vp = (info) => (info.project.name === 'phone' ? '390x844' : '1440x900');
async function setup(page, lang) { await page.addInitScript(instrument(FILE2CLIP, 1)); await page.addInitScript(({ lang }) => { try { sessionStorage.setItem('athar-intro-v1.4.2', 'done'); localStorage.setItem('athar-pact-lang', lang); } catch (e) {} }, { lang }); page.__errors = []; page.__net = []; page.on('pageerror', (e) => page.__errors.push(String(e))); page.on('console', (m) => { if (m.type() === 'error') page.__errors.push(m.text()); }); page.on('requestfailed', (r) => { const f = r.failure(); if (!f || f.errorText !== 'net::ERR_ABORTED') page.__net.push(r.url()); }); page.on('response', (r) => { if (r.status() >= 400) page.__net.push(r.status() + ' ' + r.url()); }); }
async function noCache(page) { const cdp = await page.context().newCDPSession(page); await cdp.send('Network.enable'); await cdp.send('Network.setCacheDisabled', { cacheDisabled: true }); }
async function open(page, n, lang, hash) { await page.goto(BASE + '/' + (lang ? '?lang=' + lang : '') + (hash || hashFor(n)), { waitUntil: 'load' }); await page.waitForFunction(() => !!window.AtharGuide, null, { timeout: 20000 }); await page.waitForFunction((n) => window.__qaVisible().n === n, n, { timeout: 15000 }); await page.waitForTimeout(900); }
/* in-page WCAG measurement (same algorithm as qa/audit-v172.json): effective background by compositing ancestor backgrounds (rgb / rgba / color(srgb …)), relative luminance, 4.5:1 body / 3:1 large */
const MEASURE = `window.__m = (function(){
  function parseRGB(s){ s=s||''; let m=/^color\\(srgb\\s+([\\d.]+)\\s+([\\d.]+)\\s+([\\d.]+)(?:\\s*\\/\\s*([\\d.]+%?))?\\)/.exec(s); if(m){ const a=m[4]==null?1:(m[4].endsWith('%')?parseFloat(m[4])/100:parseFloat(m[4])); return {r:+m[1]*255,g:+m[2]*255,b:+m[3]*255,a}; } m=/rgba?\\(([^)]+)\\)/.exec(s); if(!m) return null; const p=m[1].split(/[ ,\\/]+/).map(parseFloat); return {r:p[0],g:p[1],b:p[2],a:p.length>3?p[3]:1}; }
  function lum(c){ const f=v=>{v/=255; return v<=0.03928? v/12.92 : Math.pow((v+0.055)/1.055,2.4)}; return 0.2126*f(c.r)+0.7152*f(c.g)+0.0722*f(c.b); }
  function ratio(a,b){ const l1=lum(a), l2=lum(b); return (Math.max(l1,l2)+0.05)/(Math.min(l1,l2)+0.05); }
  function blend(fg,bg){ const a=fg.a==null?1:fg.a; return {r:fg.r*a+bg.r*(1-a), g:fg.g*a+bg.g*(1-a), b:fg.b*a+bg.b*(1-a), a:1}; }
  function hex(c){ const h=v=>('0'+Math.round(v).toString(16)).slice(-2); return '#'+h(c.r)+h(c.g)+h(c.b); }
  function visible(el){ const r=el.getBoundingClientRect(); if(r.width<1||r.height<1) return false; const cs=getComputedStyle(el); return !(cs.visibility==='hidden'||cs.display==='none'||parseFloat(cs.opacity)===0); }
  function effectiveBg(el){ let layers=[]; let e=el; while(e && e!==document.documentElement){ const cs=getComputedStyle(e); const bg=parseRGB(cs.backgroundColor); if(bg && bg.a>0){ layers.push(bg); if(bg.a>=1) break; } e=e.parentElement; } let base=parseRGB(getComputedStyle(document.body).backgroundColor)||{r:255,g:255,b:255,a:1}; if(base.a===0) base={r:255,g:255,b:255,a:1}; for(let i=layers.length-1;i>=0;i--) base=blend(layers[i], base); return base; }
  function sel(el){ const t=el.getAttribute('data-testid'); return (t? '[data-testid='+t+']' : el.tagName.toLowerCase()+(el.classList.length?'.'+[...el.classList].slice(0,2).join('.'):'')); }
  function contrast(root){ const out=[]; const w=document.createTreeWalker(root, NodeFilter.SHOW_TEXT); let n; const seen=new Set(); while((n=w.nextNode())){ const txt=(n.textContent||'').trim(); if(!txt) continue; const el=n.parentElement; if(!el||seen.has(el)||!visible(el)) continue; seen.add(el); const cs=getComputedStyle(el); let fg=parseRGB(cs.color); if(!fg) continue; const bg=effectiveBg(el); if(fg.a<1) fg=blend(fg,bg); const size=parseFloat(cs.fontSize), weight=parseInt(cs.fontWeight,10)||400; const large=size>=24||(size>=18.66&&weight>=700); const r=ratio(fg,bg); out.push({sel:sel(el), text:txt.slice(0,40), fg:hex(fg), bg:hex(bg), ratio:Math.round(r*100)/100, need:large?3:4.5, pass:r>=(large?3:4.5)}); } return out; }
  return {contrast, visible};
})();`;

test.describe(`v${V} section 10 audit fixes`, () => {
  test('release metadata: version everywhere; slide 47 = NAR-s52 EN + AR (Scribe-verified, cues s47-*), NAR-s47 retired; laptop render set derived from the edited render with a pinned monogram composite (reproducible); secondary-row citation; SHA256SUMS; no service worker; notes', async () => {
    expect(BRAND.version).toBe(V); expect(TOK.version).toBe(V); expect(ASSETS.version).toBe(V); expect(TABLE.version).toBe(V); expect(MANIFEST.version.startsWith('v' + V)).toBe(true); expect(JSON.parse(read('features.json')).version).toBe(V); expect(JSON.parse(read('features/exec-films/films.json')).version).toBe(V);
    for (const loc of ['en', 'ar']) expect(JSON.parse(read(`dist/locales/impact-tiers.${loc}.json`)).version).toBe(V);
    for (const js of ['api-licences', 'athar-os', 'cobrand', 'impact-tiers', 'video-player', 'exec-film-player', 'exec-team', 'intro-gate', 'narration', 'brand-section']) expect(read(`dist/js/${js}.js`), js).toContain(`var VERSION = 'v${V}'`);
    expect(read('dist/js/img-guard.js')).toContain(`version: 'v${V}'`); expect(read('dist/js/brand-data.js')).toContain(`"version":"${V}"`); expect(read('dist/assets/brand-section.css')).toContain('v' + V);
    const html = read('dist/index.html'); expect(html).toContain(`data-deck-version="${V}"`); expect(html).toContain(`'v${V}'`); const stamps = [...html.matchAll(/\?v=([0-9.]+)/g)].map((m) => m[1]); expect(stamps.length).toBeGreaterThanOrEqual(28); expect([...new Set(stamps)]).toEqual([V]);
    /* no service worker in this build (cache busting = ?v= stamps + no-store) */
    for (const f of ['dist/sw.js', 'dist/service-worker.js']) expect(fs.existsSync(path.join(ROOT, f)), f).toBe(false); expect(html).not.toMatch(/serviceWorker\.register/);
    /* A-07 narration */
    const sums = read('SHA256SUMS.txt'); const r = TABLE.slides.find((x) => x.n === 47); expect(r.clipId).toBe('NAR-s52'); expect(r.ar.clipId).toBe('NAR-s52-ar'); expect(r.file).toBe('/audio/guide/slides/NAR-s52-s-brand-typography.mp3'); expect(r.ar.file).toBe('/audio/guide/slides/NAR-s52-s-brand-typography.ar.mp3');
    for (const e of [r, r.ar]) { const p = path.join(ROOT, 'dist', e.file); expect(fs.existsSync(p), e.file).toBe(true); expect(sha256(fs.readFileSync(p))).toBe(e.sha256); expect(sums).toContain(e.sha256 + '  ./dist' + e.file); expect(e.durationSec).toBeGreaterThan(30); expect(e.source.voice).toContain('George'); expect(e.source.modelRequested).toBe('eleven_multilingual_v2'); expect(e.source.contentCheck).toContain('Scribe'); expect(e.cues.length).toBe(8); expect(e.cues.every((c) => /^s47-c\d$/.test(c.anchor))).toBe(true); expect(e.cues[e.cues.length - 1].end).toBeLessThanOrEqual(e.durationSec + 0.05); }
    expect(r.text).toContain('IBM Plex Sans Medium'); expect(r.ar.text).toContain('ميديوم'); expect(r.source.contentCheck).toContain('0.000'); expect(r.ar.source.contentCheck).toContain('0.015');
    expect(MANIFEST.segments.filter((s) => s.slideId === 's-brand-typography').map((s) => s.clipId).sort()).toEqual(['NAR-s52', 'NAR-s52-ar']);
    for (const gone of ['NAR-s47-s-brand-typography.mp3', 'NAR-s47-s-brand-typography.ar.mp3']) { expect(fs.existsSync(path.join(ROOT, 'dist/audio/guide/slides', gone)), gone).toBe(false); expect(sums).not.toContain(gone); }
    expect(BRAND.narration.clips['s-brand-typography']).toEqual({ en: 'NAR-s52', ar: 'NAR-s52-ar' });
    /* A-08 laptop render set */
    expect(LAPTOP).toHaveLength(3); expect(LAPTOP.map((i) => i.role).sort()).toEqual(['jpg', 'webp1x', 'webp2x']);
    for (const it of LAPTOP) { expect(it.sourceSha256).toBe(LAPTOP_SRC_SHA); expect(it.file.match(/\.([0-9a-f]{10})\./)[1]).toBe(it.sha256.slice(0, 10)); for (const dir of ['features/brand/assets', 'dist/assets/brand']) { const p = path.join(ROOT, dir, it.file); expect(fs.existsSync(p), p).toBe(true); expect(sha256(fs.readFileSync(p))).toBe(it.sha256); } expect(sums).toContain(it.sha256 + '  ./dist/assets/brand/' + it.file);
      const pl = it.logoComposite.placements; expect(pl).toHaveLength(1); expect(pl[0].kind).toBe('monogram'); expect(pl[0].h).toBeGreaterThanOrEqual(32); expect(pl[0].opacity).toBe(1); expect(pl[0].x).toBe(414); expect(pl[0].y).toBe(540); expect(it.logoComposite.method).toContain('PINNED'); expect(it.logoComposite.inputs.render.sha256).toBe(LAPTOP_SRC_SHA); }
    for (const old of OLD_LAPTOP) { expect(fs.existsSync(path.join(ROOT, 'dist/assets/brand', old)), old).toBe(false); expect(sums).not.toContain(old); }
    let verify = 'skipped (set V173_RENDER + V173_LOGO to the input files to re-derive the hashes)';
    if (process.env.V173_RENDER && process.env.V173_LOGO && fs.existsSync(process.env.V173_RENDER)) { const p = spawnSync('python3', [path.join(ROOT, 'scripts/v1.7.3/recomposite_laptop_render.py'), process.env.V173_RENDER, process.env.V173_LOGO, '--verify'], { encoding: 'utf8' }); verify = (p.stdout || '') + (p.stderr || ''); expect(p.status, verify).toBe(0); expect(verify).toContain('reproducible'); }
    /* A-12 */
    expect(BRAND.colourSystem.secondaryRow.citation).toContain('Table 3.1'); expect(BRAND.colourSystem.accents.map((a) => a.name)).toEqual(['Emerald', 'Sand']); expect(ACCENT_HEX).toEqual(['#405A5B', '#BEAA91']); expect(TOKEN_HEX).toHaveLength(5);
    /* hygiene */
    expect(read('dist/js/brand-section.js')).not.toMatch(/#[0-9A-Fa-f]{6}\b/); expect(read('dist/assets/brand-section.css')).not.toMatch(/#[0-9A-Fa-f]{6}\b/);
    expect(read('CHANGELOG.md')).toContain('## v' + V); expect(read('RELEASE_NOTES.md')).toContain('v' + V); expect(fs.existsSync(path.join(ROOT, 'asset-ledger-v' + V + '.csv'))).toBe(true); expect(fs.existsSync(path.join(ROOT, 'qa/audit-v172.json'))).toBe(true);
    const audit = JSON.parse(read('qa/audit-v172.json')); const open = audit.findings.filter((f) => ['P0', 'P1'].includes(f.priority) && !['fixed', 'verified-no-change'].includes(f.resolution.status)); expect(open, 'every P0/P1 resolved: ' + JSON.stringify(open.map((f) => f.id))).toEqual([]);
    write('release-metadata', [{ version: V, laptop: LAPTOP.map((i) => ({ file: i.file, sha256: i.sha256, bytes: i.bytes })), clip47: { en: r.clipId, ar: r.ar.clipId, enSec: r.durationSec, arSec: r.ar.durationSec }, verify, stamps: stamps.length }]);
  });

  for (const lang of ['en', 'ar']) for (const [n, id, k, clip] of SLIDES) test(`slide ${n} ${lang.toUpperCase()}: scroll region focusable (A-01), measured contrast AA, axe 0 violations, ${k === 1 ? 'core + secondary swatch rows, table headers (A-10/A-12)' : k === 2 ? 'NAR-s52 resolved + audible on N (A-07), fonts' : 'tiles/button/srcset/lightbox semantics (A-02…A-05, A-09), new render hashes (A-08)'}; RTL; screenshot`, async ({ page }, info) => {
    test.setTimeout(240000); const mobile = info.project.name === 'phone';
    await noCache(page); await setup(page, lang); await page.addInitScript(MEASURE); await open(page, n, lang); await page.waitForTimeout(600);
    const r = await page.evaluate(async ({ id, n }) => { const sec = document.getElementById(id); const q = (s) => sec.querySelector(s); const qa = (s) => [...sec.querySelectorAll(s)]; const body = q('.s-body'); const m = window.__m;
      let fonts = null; try { await document.fonts.ready; fonts = { sansMedium: document.fonts.check('500 16px "IBM Plex Sans"'), arabicMedium: document.fonts.check('500 16px "IBM Plex Sans Arabic"') }; } catch (e) {}
      const contrast = m.contrast(sec); const kick = q('.s-head .s-kicker'); const ths = qa('[data-testid="brand-min-sizes"] tr:first-child th');
      const tiles = qa('[data-testid="brand-product-tile"]').map((t) => { const b = t.querySelector('button.br-tile-open'); const br = b ? b.getBoundingClientRect() : { width: 0, height: 0 }; const src = t.querySelector('picture source[type="image/webp"]'); const im = t.querySelector('picture img'); const sl = t.querySelector('.br-tile-src'); return { asset: t.getAttribute('data-asset'), role: t.getAttribute('role'), labelledby: t.getAttribute('aria-labelledby'), named: !!(t.getAttribute('aria-labelledby') && document.getElementById(t.getAttribute('aria-labelledby'))), btn: !!b, btnLabel: b && b.getAttribute('aria-label'), btnW: Math.round(br.width), btnH: Math.round(br.height), srcset: src && src.srcset, sizes: src && src.sizes, imgSrc: im && im.getAttribute('src'), currentSrc: im && im.currentSrc, srcOverflow: sl ? sl.scrollWidth > sl.clientWidth + 1 : false, srcTitle: sl ? sl.title : null, composite: t.getAttribute('data-logo-composite') }; });
      const swatch = (s) => ({ hex: s.getAttribute('data-hex'), left: Math.round(s.getBoundingClientRect().left), top: Math.round(s.getBoundingClientRect().top) });
      return { active: sec.classList.contains('is-active'), hash: location.hash, dir: document.documentElement.dir, counter: (document.querySelector('footer.pagefooter .counter') || {}).textContent, badge: (document.querySelector('[data-testid="deck-version"]') || {}).textContent, visibleN: window.__qaVisible().n,
        region: body && { tabindex: body.getAttribute('tabindex'), role: body.getAttribute('role'), label: body.getAttribute('aria-label'), scrolls: body.scrollHeight > body.clientHeight + 1, sh: body.scrollHeight, ch: body.clientHeight },
        contrastTotal: contrast.length, contrastFails: contrast.filter((c) => !c.pass), contrastMin: Math.min(...contrast.map((c) => c.ratio)), kickerLS: kick ? getComputedStyle(kick).letterSpacing : null, fonts,
        ths: ths.map((t) => ({ text: t.textContent.trim(), scope: t.getAttribute('scope') })), rowHeaders: qa('[data-testid="brand-min-sizes"] tr th[scope="row"]').length,
        core: qa('[data-row="core"] [data-testid="brand-swatch"]').map(swatch), secondary: qa('[data-row="secondary"] [data-testid="brand-accent-swatch"]').map(swatch), secondaryHeading: (q('[data-testid="brand-secondary-heading"]') || {}).textContent || null, coreHeading: (q('[data-testid="brand-core-heading"]') || {}).textContent || null,
        clipId: window.AtharGuide && window.AtharGuide.clipFor ? window.AtharGuide.clipFor(id) : null, tiles, overflowX: sec.scrollWidth > sec.clientWidth + 2 }; }, { id, n });
    /* keyboard-origin focus on the scroll region → visible ring */
    await page.keyboard.press('Shift'); const ring = await page.evaluate((id) => { const b = document.getElementById(id).querySelector('.s-body'); b.focus(); const cs = getComputedStyle(b); return { fv: b.matches(':focus-visible'), style: cs.outlineStyle, width: cs.outlineWidth, color: cs.outlineColor, active: document.activeElement === b }; }, id);
    await page.evaluate(() => document.activeElement && document.activeElement.blur());
    /* axe-core on the section */
    await page.addScriptTag({ content: AXE }); const axe = await page.evaluate(async (id) => { const res = await window.axe.run(document.getElementById(id), { runOnly: { type: 'tag', values: ['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa', 'wcag22aa', 'best-practice'] }, resultTypes: ['violations'] }); return { version: window.axe.version, violations: res.violations.map((v) => ({ id: v.id, impact: v.impact, count: v.nodes.length, targets: v.nodes.slice(0, 3).map((x) => x.target.join(' ')) })) }; }, id);
    let narration = null; if (k === 2) { await page.keyboard.press('n'); await page.waitForTimeout(3500); narration = await page.evaluate(() => { const g = document.getElementById('athar-narration'); return { audible: window.__qaAudible(), state: g && g.getAttribute('data-state'), clip: g && g.getAttribute('data-clip') }; }); await page.keyboard.press('n'); await page.waitForTimeout(300); }
    let lightbox = null; if (k === 3) {
      const tileSel = '[data-testid="brand-product-tile"][data-asset="render-laptop-phone-dashboard"]';
      await page.evaluate((s) => { const b = document.querySelector(s + ' button.br-tile-open'); b.scrollIntoView({ block: 'center' }); b.focus(); }, tileSel); await page.keyboard.press('Enter'); await page.waitForSelector('[data-testid="brand-lightbox"]', { timeout: 8000 }); await page.waitForTimeout(400);
      const opened = await page.evaluate(() => { const lb = document.querySelector('[data-testid="brand-lightbox"]'); const rc = lb.getBoundingClientRect(); const c = lb.querySelector('.br-lb-close'); const cr = c.getBoundingClientRect(); const lab = document.getElementById(lb.getAttribute('aria-labelledby') || ''); const img = lb.querySelector('img'); return { role: lb.getAttribute('role'), modal: lb.getAttribute('aria-modal'), labelledby: lb.getAttribute('aria-labelledby'), name: lab ? lab.textContent.trim() : null, ariaLabel: lb.getAttribute('aria-label'), popover: lb.hasAttribute('popover'), w: Math.round(rc.width), h: Math.round(rc.height), closeW: Math.round(cr.width), closeH: Math.round(cr.height), closeLeft: Math.round(cr.left), closeLabel: c.getAttribute('aria-label'), activeIsClose: document.activeElement === c, img: img && img.currentSrc, bodyFlag: document.body.classList.contains('br-lightbox-open'), srcClamp: getComputedStyle(lb.querySelector('.br-tile-src')).webkitLineClamp }; });
      await page.screenshot({ path: path.join(SHOTS, `${PREFIX}-slide-48-lightbox-${lang}-${vp(info)}.png`) });
      const trap = []; for (const key of ['Tab', 'Tab', 'Tab', 'Shift+Tab']) { await page.keyboard.press(key); trap.push(await page.evaluate(() => { const lb = document.querySelector('[data-testid="brand-lightbox"]'); return lb && lb.contains(document.activeElement) ? (document.activeElement.getAttribute('data-testid') || 'inside') : 'OUTSIDE:' + (document.activeElement && document.activeElement.tagName); })); }
      await page.keyboard.press('Escape'); await page.waitForTimeout(400);
      const after = await page.evaluate((s) => { const t = document.querySelector(s); const b = t.querySelector('button.br-tile-open'); return { closed: !document.querySelector('[data-testid="brand-lightbox"]'), focusReturned: document.activeElement === b, overviewOpened: !!document.querySelector('[data-testid="overview"]'), role: t.getAttribute('role'), btnLabel: b.getAttribute('aria-label'), hash: location.hash, bodyFlag: document.body.classList.contains('br-lightbox-open') }; }, tileSel);
      lightbox = { opened, trap, after };
    }
    await page.screenshot({ path: path.join(SHOTS, `${PREFIX}-slide-${n}-${lang}-${vp(info)}.png`) });
    write(`slide-${n}-${lang}-` + info.project.name, [{ ...r, ring, axe, narration, lightbox, errors: page.__errors, failedRequests: page.__net }]);
    expect(r.active).toBe(true); expect(r.visibleN).toBe(n); expect(r.hash).toBe(hashFor(n)); expect(r.dir).toBe(lang === 'ar' ? 'rtl' : 'ltr'); expect(r.counter).toContain(String(n)); expect(r.counter).toContain('48'); expect(r.badge).toBe('v' + V); expect(r.overflowX).toBe(false);
    /* A-01 */ expect(r.region.tabindex).toBe('0'); expect(r.region.role).toBe('region'); expect((r.region.label || '').length).toBeGreaterThan(5); expect(ring.active).toBe(true); expect(ring.style).toBe('solid'); expect(parseFloat(ring.width)).toBeGreaterThanOrEqual(3);
    /* contrast */ expect(r.contrastTotal).toBeGreaterThan(40); expect(r.contrastFails, JSON.stringify(r.contrastFails.slice(0, 5))).toEqual([]); expect(r.contrastMin).toBeGreaterThanOrEqual(4.5);
    /* axe */ expect(axe.violations.filter((v) => ['critical', 'serious'].includes(v.impact)), JSON.stringify(axe.violations)).toEqual([]); expect(axe.violations, JSON.stringify(axe.violations)).toEqual([]);
    /* A-06 */ if (lang === 'ar') expect(['0px', 'normal']).toContain(r.kickerLS);
    /* A-13 */ if (!mobile && k !== 2) expect(r.region.scrolls, `body ${r.region.sh}/${r.region.ch}`).toBe(false);
    expect(r.fonts.sansMedium).toBe(true); expect(r.fonts.arabicMedium).toBe(true); expect(r.clipId).toBe(clip + (lang === 'ar' ? '-ar' : ''));
    if (k === 1) { expect(r.ths.map((t) => t.text.length > 0)).toEqual([true, true, true]); expect(r.ths.every((t) => t.scope === 'col')).toBe(true); expect(r.rowHeaders).toBe(4);
      expect(r.core.map((s) => s.hex)).toEqual(TOKEN_HEX); expect(r.secondary.map((s) => s.hex)).toEqual(ACCENT_HEX); expect(r.secondaryHeading).toMatch(/3\.1/); expect(r.coreHeading).toMatch(/tokens_v1/);
      if (!mobile) { const first = r.core[0].left, last = r.core[4].left; expect(lang === 'ar' ? first > last : first < last, 'swatch row mirrored for ' + lang).toBe(true); expect(r.secondary[0].top).toBeGreaterThan(r.core[0].top); } }
    if (k === 2) { expect(narration.state).toBe('playing'); expect(narration.audible && narration.audible.src).toBe('NAR-s52-s-brand-typography' + (lang === 'ar' ? '.ar' : '') + '.mp3'); }
    if (k === 3) { expect(r.tiles).toHaveLength(11); for (const t of r.tiles) { expect(t.role, t.asset).toBe('group'); expect(t.named, t.asset).toBe(true); expect(t.btn, t.asset).toBe(true); expect(t.btnLabel, t.asset).toMatch(lang === 'ar' ? /^تكبير: ./ : /^Enlarge: ./); expect(t.btnW, t.asset).toBeGreaterThanOrEqual(44); expect(t.btnH, t.asset).toBeGreaterThanOrEqual(44); expect(t.srcOverflow, t.asset + ' source line overflows').toBe(false); expect(t.imgSrc).toMatch(/\.jpg$/); if (t.asset.startsWith('__')) expect(t.srcset).toMatch(/ 1x, .* 2x$/); else { expect(t.srcset).toMatch(/ \d+w, .* \d+w$/); expect(t.sizes).toContain('vw'); } }
      const lap = r.tiles.find((t) => t.asset === 'render-laptop-phone-dashboard'); expect(lap.composite).toBe('1'); expect(LAPTOP.some((i) => lap.currentSrc.includes(i.sha256.slice(0, 10)))).toBe(true); expect(lap.srcTitle).toContain('ohVo7cVcwn');
      if (!mobile) { const lefts = r.tiles.filter((t) => !t.asset.startsWith('agent')).map((t) => t.asset); expect(lefts[0]).toBe('render-stationery-flat-lay'); }
      expect(lightbox.opened.role).toBe('dialog'); expect(lightbox.opened.modal).toBe('true'); expect(lightbox.opened.labelledby).toBeTruthy(); expect(lightbox.opened.name).toContain(lang === 'ar' ? 'لوحة تحكم' : 'Laptop + phone dashboard'); expect(lightbox.opened.ariaLabel).toBeNull(); expect(lightbox.opened.closeW).toBeGreaterThanOrEqual(44); expect(lightbox.opened.closeH).toBeGreaterThanOrEqual(44); expect(lightbox.opened.activeIsClose).toBe(true); expect(lightbox.opened.img).toContain('/assets/brand/gallery/render-laptop-phone-dashboard'); expect(lightbox.opened.w).toBeGreaterThanOrEqual(page.viewportSize().width - 2); expect(lightbox.opened.srcClamp).toBe('none');
      if (!mobile) expect(lang === 'ar' ? lightbox.opened.closeLeft < 100 : lightbox.opened.closeLeft > 1300, 'Close on the inline-end side').toBe(true);
      expect(lightbox.trap.every((t) => !t.startsWith('OUTSIDE')), JSON.stringify(lightbox.trap)).toBe(true); expect(new Set(lightbox.trap).size).toBe(2);
      expect(lightbox.after.closed).toBe(true); expect(lightbox.after.focusReturned).toBe(true); expect(lightbox.after.overviewOpened).toBe(false); expect(lightbox.after.role).toBe('group'); expect(lightbox.after.btnLabel).toMatch(lang === 'ar' ? /^تكبير: / : /^Enlarge: /); expect(lightbox.after.hash).toBe(hashFor(48)); expect(lightbox.after.bodyFlag).toBe(false); }
    expect(page.__errors).toEqual([]); expect(page.__net).toEqual([]);
  });

  test('served + routes: build-info v' + V + ' @ deployed HEAD; new clips + laptop files 200/sha256/immutable, retired files 404; #/29 alias kept in the address bar for #/29, #/28 and #slide-4x entries; deep links 32/38/39–45 unchanged; runtime + reload; keyboard 45 → 46 → 45', async ({ page }) => {
    test.setTimeout(300000);
    const info = await (await page.request.get(BASE + '/build-info.json' + cb(), { headers: NO_CACHE })).json(); expect(info.version).toBe(V); expect((info.commit || '').toLowerCase()).toBe(EXPECT_COMMIT);
    const served = [];
    for (const it of LAPTOP) { const r = await page.request.get(BASE + ASSETS.distBase + it.file + cb(), { headers: NO_CACHE, timeout: 120000 }); const body = await r.body(); served.push({ file: it.file, status: r.status(), cc: r.headers()['cache-control'] }); expect(r.status(), it.file).toBe(200); expect(sha256(body)).toBe(it.sha256); expect(r.headers()['cache-control'] || '').toContain('immutable'); }
    for (const old of OLD_LAPTOP) { const r = await page.request.get(BASE + ASSETS.distBase + old + cb(), { headers: NO_CACHE }); expect(r.status(), old).toBe(404); }
    const row = TABLE.slides.find((x) => x.n === 47); for (const e of [row, row.ar]) { const r = await page.request.get(BASE + e.file + cb(), { headers: NO_CACHE }); expect(r.status(), e.file).toBe(200); expect(sha256(await r.body())).toBe(e.sha256); }
    for (const gone of ['/audio/guide/slides/NAR-s47-s-brand-typography.mp3', '/audio/guide/slides/NAR-s47-s-brand-typography.ar.mp3']) { const r = await page.request.get(BASE + gone + cb(), { headers: NO_CACHE }); expect(r.status(), gone).toBe(404); }
    const targets = [32, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48].map((n) => [n, hashFor(n)]).concat([[46, '#/28/brand-1'], [47, '#/28/brand-2'], [48, '#/28/brand-3'], [46, '#slide-46'], [47, '#slide-47'], [48, '#slide-48']]); const deep = [];
    for (const lang of ['en', 'ar']) for (const [n, h] of targets) { const ctx = await page.context().browser().newContext({ viewport: page.viewportSize() }); const p2 = await ctx.newPage(); await setup(p2, lang); await p2.goto(BASE + '/?lang=' + lang + h, { waitUntil: 'load' }); await p2.waitForFunction(() => !!window.AtharGuide, null, { timeout: 20000 }); await p2.waitForFunction((n) => window.__qaVisible().n === n, n, { timeout: 20000 }); await p2.waitForFunction((want) => location.hash === want, hashFor(n), { timeout: 5000 }); const v = await p2.evaluate(() => ({ ...window.__qaVisible(), hash: location.hash, counter: (document.querySelector('footer.pagefooter .counter') || {}).textContent })); deep.push({ lang, n, requested: h, ...v, errors: p2.__errors, failed: p2.__net }); expect(v.n, lang + ' ' + h).toBe(n); expect(v.hash, lang + ' ' + h).toBe(hashFor(n)); expect(v.counter).toContain(String(n)); expect(p2.__errors).toEqual([]); expect(p2.__net).toEqual([]); await ctx.close(); }
    /* runtime: from slide 12 set the public alias; reload keeps it; keyboard hand-over 45 → 46 → 45 */
    const ctx = await page.context().browser().newContext({ viewport: page.viewportSize() }); const p3 = await ctx.newPage(); await setup(p3, 'en'); await open(p3, 12, 'en');
    await p3.evaluate(() => { location.hash = '#/29/brand-2'; }); await p3.waitForFunction(() => window.__qaVisible().n === 47, null, { timeout: 10000 }); await p3.waitForFunction(() => location.hash === '#/29/brand-2', null, { timeout: 5000 }); const rt = await p3.evaluate(() => ({ ...window.__qaVisible(), hash: location.hash }));
    await p3.reload({ waitUntil: 'load' }); await p3.waitForFunction(() => !!window.AtharGuide, null, { timeout: 20000 }); await p3.waitForFunction(() => window.__qaVisible().n === 47, null, { timeout: 15000 }); await p3.waitForFunction(() => location.hash === '#/29/brand-2', null, { timeout: 5000 }); const rl = await p3.evaluate(() => ({ ...window.__qaVisible(), hash: location.hash }));
    await open(p3, 45, 'en'); await p3.keyboard.press('ArrowRight'); await p3.waitForFunction(() => window.__qaVisible().n === 46, null, { timeout: 8000 }); await p3.waitForFunction(() => location.hash === '#/29/brand-1', null, { timeout: 5000 }); const k1 = await p3.evaluate(() => ({ ...window.__qaVisible(), hash: location.hash }));
    await p3.keyboard.press('ArrowLeft'); await p3.waitForFunction(() => window.__qaVisible().n === 45, null, { timeout: 8000 }); const k2 = await p3.evaluate(() => ({ ...window.__qaVisible(), hash: location.hash }));
    /* the rail + overview still carry 10 · Brand after 09 */
    const rail = await p3.evaluate(() => [...document.querySelectorAll('nav.rail ol li .rail-n')].map((e) => e.textContent).join(','));
    write('served-routes-' + test.info().project.name, [{ servedCommit: info.commit, servedVersion: info.version, served, deep, runtime: rt, reload: rl, k1, k2, rail, errors: p3.__errors }]);
    expect(rt.slideId).toBe('s-brand-typography'); expect(rl.slideId).toBe('s-brand-typography'); expect(k1.slideId).toBe('s-brand-foundations'); expect(k1.hash).toBe('#/29/brand-1'); expect(k2.slideId).toBe('s-exec-lorenzo'); expect(k2.hash).toBe('#/28/exec-6'); expect(rail).toBe('01,02,03,04,05,06,07,08,09,10'); expect(p3.__errors).toEqual([]); await ctx.close();
  });
});
