// Athar deck v1.7.0 — FINAL RELEASE suite. Five Section 09 films (Al Ameri, Ferreira da Cunha, Khalid, Unwalla, Avitabile), every served film asset
// content-hashed (<name>.<sha256[0:10]>.<ext>, immutable), no-store on every non-content-addressed file, ?v=1.7.0 on every bundle tag.
// (1) release metadata — package / features / films.json / every VERSION literal / narration table + manifest / locales / index.html stamps all read 1.7.0; the five
//     films' 30 served files are hashed with their own sha256 and listed in SHA256SUMS; CHANGELOG + RELEASE_NOTES + README carry the v1.7.0 entries and the open decisions;
// (2) every card × EN/AR (cache-disabled context, 1440x900 + 390x844): the <video> resolves to the hashed 1080p (desktop) / 720p (phone) file with the films.json duration
//     (Khalid 50.0 s, the others 40.0 s, ± 0.5), hashed poster, hashed EN/AR tracks (default follows the language), title/role copy, plays with the language's cues showing —
//     with a poster screenshot and a mid-playback screenshot per card, and the Section 09 overview tiles 40–45 (screenshot);
// (3) served: the 30 film files 200 + sha256 + immutable; '/', index.html, build-info.json, js/exec-films.js answer 200 + no-store to a Cache-Control: no-cache request;
//     build-info commit == EXPECT_COMMIT (deployed HEAD), version 1.7.0, five shipped films with sha256; the 24 retired un-hashed paths (Khalid v1.6.2 + the three films
//     hashed in v1.7.0) answer 404; the served index.html carries ?v=1.7.0 on every bundle tag and no other stamp;
// (4) all 45 slides EN + AR with 0 console errors / 0 failed requests; deep links 32, 38, 39–45 in both languages land (RTL in AR).
// Usage: GUIDE_BASE=https://host EXPECT_COMMIT=<sha> SHOT_PREFIX=after SHOTS_DIR=/path PW_WORKERS=2 node ../../node_modules/@playwright/test/cli.js test -c playwright.config.mjs
import { test, expect } from '../../node_modules/@playwright/test/index.mjs';
import fs from 'node:fs'; import path from 'node:path'; import crypto from 'node:crypto'; import { execSync } from 'node:child_process';
import { instrument, FILE2CLIP, hashFor, warmUp } from '../v154/lib.mjs';
const HERE = path.dirname(new URL(import.meta.url).pathname); const ROOT = path.join(HERE, '../..'); const BASE = process.env.GUIDE_BASE || 'http://127.0.0.1:4170'; const PREFIX = process.env.SHOT_PREFIX || 'after'; const SHOTS = process.env.SHOTS_DIR || path.join(HERE, 'screenshots');
const RESULTS = path.join(HERE, 'results'); fs.mkdirSync(RESULTS, { recursive: true }); fs.mkdirSync(SHOTS, { recursive: true });
const read = (rel) => fs.readFileSync(path.join(ROOT, rel), 'utf8'); const sha256 = (buf) => crypto.createHash('sha256').update(buf).digest('hex');
const PKG = JSON.parse(read('package.json')); const FEAT = JSON.parse(read('features.json')); const FILMS = JSON.parse(read('features/exec-films/films.json')); const F = (r) => FILMS.distBase + r;
const TABLE = JSON.parse(read('dist/narration/slide-narration.json')); const MANIFEST = JSON.parse(read('dist/narration/narration-manifest.json'));
const EXPECT_COMMIT = (process.env.EXPECT_COMMIT || execSync('git rev-parse HEAD', { cwd: HERE }).toString().trim()).toLowerCase(); const NO_CACHE = { 'Cache-Control': 'no-cache', Pragma: 'no-cache' }; const cb = () => '?cb=' + Date.now();
const V = '1.7.0'; const ORDER = ['s-exec-intro', 's-exec-al-ameri', 's-exec-ferreira-da-cunha', 's-exec-khalid', 's-exec-unwalla', 's-exec-lorenzo'];
const CARDS = [['al-ameri', 2, 41], ['ferreira-da-cunha', 3, 42], ['khalid', 4, 43], ['unwalla', 5, 44], ['lorenzo', 6, 45]]; const FILM_ORDER = ['khalid', 'al-ameri', 'ferreira-da-cunha', 'unwalla', 'lorenzo'];
const FILES = (f) => [['mp4', f.mp4, f.mp4Sha256], ['mp4Mobile', f.mp4Mobile, f.mp4MobileSha256], ['poster', f.poster, f.posterSha256], ['posterWebp', f.posterWebp, f.posterWebpSha256], ['vttEn', f.captions.en, f.captionsSha256.en], ['vttAr', f.captions.ar, f.captionsSha256.ar]];
const HASHED = /\.([0-9a-f]{10})\.(mp4|jpg|webp|vtt)$/;
const RETIRED = [ /* v1.6.2 Khalid un-hashed names + v1.7.0 un-hashed names of the three films hashed in this release */
  ...['athar-origins-of-impact-ep01-muhammed-khalid-1080p.mp4', 'athar-origins-of-impact-ep01-muhammed-khalid-720p.mp4', 'athar-origins-of-impact-ep01-muhammed-khalid-poster-18s8.jpg', 'athar-origins-of-impact-ep01-muhammed-khalid-poster-18s8.webp', 'athar-origins-of-impact-ep01-muhammed-khalid.en.vtt', 'athar-origins-of-impact-ep01-muhammed-khalid.ar.vtt'].map((n) => F('khalid/' + n)),
  ...['al-ameri', 'ferreira-da-cunha', 'unwalla'].flatMap((id) => Object.keys(FILMS.films[id].hashedFilenames.map).map((n) => F(id + '/' + n)))
];
const write = (n, rows) => fs.writeFileSync(path.join(RESULTS, n + '.json'), JSON.stringify({ base: BASE, version: PKG.version, expectCommit: EXPECT_COMMIT, written: new Date().toISOString(), rows }, null, 1));
const vp = (info) => (info.project.name === 'phone' ? '390x844' : '1440x900');
async function setup(page, lang) { await page.addInitScript(instrument(FILE2CLIP, 1)); await page.addInitScript(({ lang }) => { try { sessionStorage.setItem('athar-intro-v1.4.2', 'done'); localStorage.setItem('athar-pact-lang', lang); } catch (e) {} }, { lang }); page.__errors = []; page.__net = []; page.on('pageerror', (e) => page.__errors.push(String(e))); page.on('console', (m) => { if (m.type() === 'error') page.__errors.push(m.text()); }); page.on('requestfailed', (r) => { const f = r.failure(); if (!f || f.errorText !== 'net::ERR_ABORTED') page.__net.push('FAILED ' + (f ? f.errorText : '') + ' ' + r.url()); }); page.on('response', (r) => { if (r.status() >= 400) page.__net.push(r.status() + ' ' + r.url()); }); }
async function open(page, n, lang) { await page.goto(BASE + '/' + (lang ? '?lang=' + lang : '') + hashFor(n), { waitUntil: 'load' }); await page.waitForFunction(() => !!window.AtharGuide, null, { timeout: 20000 }); await page.waitForFunction((n) => window.__qaVisible().n === n, n, { timeout: 15000 }); }

test.describe(`v${PKG.version}`, () => {
  test.beforeAll(async () => { /* cold-start warm-up (per worker) — recorded, never fatal */ const w = await warmUp(BASE, { films: FILMS }); write('warmup-' + test.info().project.name + '-w' + test.info().workerIndex, [w]); });

  test('release metadata: 1.7.0 everywhere, five shipped films with 30 content-hashed files in SHA256SUMS, narration table 45 rows, docs carry the release entries', async () => {
    expect(PKG.version).toBe(V); expect(FEAT.version).toBe(V); expect(FILMS.version).toBe(V); expect(TABLE.version).toBe(V); expect(MANIFEST.version.startsWith('v' + V)).toBe(true);
    for (const loc of ['en', 'ar']) expect(JSON.parse(read(`dist/locales/impact-tiers.${loc}.json`)).version).toBe(V);
    for (const js of ['api-licences', 'athar-os', 'cobrand', 'impact-tiers', 'video-player', 'exec-film-player', 'exec-team', 'intro-gate', 'narration']) expect(read(`dist/js/${js}.js`), js).toContain(`var VERSION = 'v${V}'`);
    expect(read('dist/js/img-guard.js')).toContain(`version: 'v${V}'`); expect(read('dist/js/exec-films.js')).toContain(`"version": "${V}"`);
    const html = read('dist/index.html'); expect(html).toContain(`data-deck-version="${V}"`); expect(html).toContain(`<meta name="application-version" content="${V}" />`); expect(html).toContain(`'v${V}'`);
    const stamps = [...html.matchAll(/\?v=([0-9.]+)/g)].map((m) => m[1]); expect(stamps.length).toBeGreaterThanOrEqual(24); expect([...new Set(stamps)]).toEqual([V]);
    expect(Object.keys(FILMS.films)).toEqual(FILM_ORDER); const sums = read('SHA256SUMS.txt'); const rows = [];
    for (const id of FILM_ORDER) { const f = FILMS.films[id]; expect(f.status, id).toBe('shipped'); expect(f.durationSec, id).toBe(id === 'khalid' ? 50 : 40); expect(f.durationLabel, id).toBe(id === 'khalid' ? '0:50' : '0:40'); expect(f.hashedFilenames && f.hashedFilenames.map, id + ' hashedFilenames').toBeTruthy();
      for (const [key, rel, sha] of FILES(f)) { expect(rel, id + '.' + key).toMatch(HASHED); expect(rel.match(HASHED)[1], id + '.' + key + ' hash prefix').toBe(sha.slice(0, 10)); const p = path.join(ROOT, 'features/exec-films/assets', rel); expect(fs.existsSync(p), rel).toBe(true); expect(sha256(fs.readFileSync(p)), rel).toBe(sha); expect(sums, rel).toContain(sha + '  ./dist' + F(rel)); expect(fs.existsSync(path.join(ROOT, 'dist', F(rel))), 'dist ' + rel).toBe(true); rows.push({ id, key, rel, sha256: sha }); } }
    expect(rows).toHaveLength(30); expect(TABLE.slides.map((x) => x.n)).toEqual(Array.from({ length: 45 }, (_, i) => i + 1)); for (const [who, , n] of CARDS) { const r = TABLE.slides.find((x) => x.n === n); expect(r.slideId, 'slide ' + n).toBe('s-exec-' + who); expect(r.file, 'slide ' + n).toMatch(/^\/audio\/guide\/slides\/NAR-s\d+-s-exec-/); expect(sums).toContain(r.sha256 + '  ./dist' + r.file); }
    const cl = read('CHANGELOG.md'), rn = read('RELEASE_NOTES.md'), rd = read('README.md'); expect(cl).toContain('## v1.7.0'); expect(rn).toContain('v1.7.0'); expect(rn).toContain('v1.6.2'); for (const s of ['Khalid', 'untrimmed', 'Lorenzo', 'LinkedIn', 'pkill -x node', 'sandbox']) { expect(rd, 'README ' + s).toContain(s); }
    write('release-metadata', [{ version: V, stamps: stamps.length, files: rows, retiredPaths: RETIRED }]);
  });

  for (const lang of ['en', 'ar']) for (const [who, k, n] of CARDS) test(`${who} ${lang.toUpperCase()} (cache disabled): hashed ${who === 'khalid' ? '50 s' : '40 s'} file, hashed poster + EN/AR tracks, plays with ${lang} cues; poster + mid-playback screenshots${who === 'lorenzo' ? '; overview tiles 40–45' : ''}`, async ({ page }, info) => {
    test.setTimeout(240000); const mobile = info.project.name === 'phone'; const f = FILMS.films[who]; const SEL = `#s-exec-${who} video[data-narration-pause]`;
    const cdp = await page.context().newCDPSession(page); await cdp.send('Network.enable'); await cdp.send('Network.setCacheDisabled', { cacheDisabled: true }); await setup(page, lang); await open(page, n, lang); await page.waitForTimeout(800);
    const idle = await page.evaluate(async ({ sel, who }) => { const v = document.querySelector(sel), fig = v.closest('.efp'), sec = document.getElementById('s-exec-' + who); await new Promise((r) => { if (v.readyState >= 1) r(); else v.addEventListener('loadedmetadata', r, { once: true }); }); const pi = new Image(); const posterOk = await new Promise((r) => { pi.onload = () => r(pi.naturalWidth > 0); pi.onerror = () => r(false); pi.src = v.poster; }); return { lang: document.documentElement.lang, dir: document.documentElement.dir, badge: document.querySelector('[data-testid="deck-version"]').textContent, html: document.documentElement.getAttribute('data-deck-version'), ids: [...document.querySelectorAll('#root section.ex-slide')].map((x) => x.id), count: window.AtharExecTeam.count, total: window.AtharExecTeam.total, active: sec.classList.contains('is-active'), n: Number(sec.getAttribute('data-n')), currentSrc: v.currentSrc || v.src, src: (v.currentSrc || v.src).split('/').pop(), poster: v.poster.split('/').pop(), posterLoaded: posterOk, duration: v.duration, dur: fig.querySelector('.efp-dur').textContent, title: fig.querySelector('.efp-title').textContent, figDir: fig.getAttribute('dir'), tracks: [...v.querySelectorAll('track')].map((t) => t.srclang + ':' + t.getAttribute('src').split('/').pop() + (t.default ? ':default' : '')), name: (sec.querySelector('.ex-letterhead-name, .ex-name') || {}).textContent, role: (sec.querySelector('.ex-letterhead-role, .ex-role') || {}).textContent, paused: v.paused }; }, { sel: SEL, who });
    await page.screenshot({ path: path.join(SHOTS, `${PREFIX}-card-${who}-${lang}-${vp(info)}.png`) });
    if (mobile) await page.tap(`#s-exec-${who} .efp-play`); else await page.click(`#s-exec-${who} .efp-play`); await page.waitForFunction((sel) => { const v = document.querySelector(sel); return !v.paused && v.currentTime > 2.5; }, SEL, { timeout: 45000 }); await page.waitForTimeout(250);
    const playing = await page.evaluate((sel) => { const v = document.querySelector(sel); return { paused: v.paused, currentTime: v.currentTime, duration: v.duration, src: (v.currentSrc || v.src).split('/').pop(), showing: [...v.textTracks].filter((t) => t.mode === 'showing').map((t) => t.language + ':' + (t.cues ? t.cues.length : -1)), controls: v.controls, guide: document.getElementById('athar-narration').getAttribute('data-state') }; }, SEL);
    await page.screenshot({ path: path.join(SHOTS, `${PREFIX}-card-${who}-playing-${lang}-${vp(info)}.png`) }); await page.evaluate((sel) => document.querySelector(sel).pause(), SEL);
    let tiles = null;
    if (who === 'lorenzo') { await page.click('[data-testid="overview-toggle"]'); await page.waitForSelector('[data-testid="overview"] button.ov-card[data-exec]', { timeout: 10000 }); await page.waitForTimeout(500); tiles = await page.evaluate(() => [...document.querySelectorAll('[data-testid="overview"] button.ov-card[data-exec]')].map((b) => b.textContent.trim())); await page.evaluate(() => { const b = document.querySelector('[data-testid="overview"] button.ov-card[data-exec="1"]'); if (b) b.scrollIntoView({ block: 'center' }); }); await page.waitForTimeout(300); await page.screenshot({ path: path.join(SHOTS, `${PREFIX}-section09-overview-${lang}-${vp(info)}.png`) }); }
    write(`card-${who}-${lang}-` + info.project.name, [{ idle, playing, tiles, errors: page.__errors, failedRequests: page.__net }]);
    expect(idle.lang).toBe(lang); expect(idle.dir).toBe(lang === 'ar' ? 'rtl' : 'ltr'); expect(idle.badge).toBe('v' + V); expect(idle.html).toBe(V); expect(idle.ids).toEqual(ORDER); expect(idle.count).toBe(6); expect(idle.total).toBe(45); expect(idle.active).toBe(true); expect(idle.n).toBe(n); expect(idle.paused).toBe(true);
    const want = (mobile ? f.mp4Mobile : f.mp4).split('/').pop(); expect(idle.src).toBe(want); expect(idle.src).toMatch(HASHED); expect(idle.currentSrc).toContain(F(mobile ? f.mp4Mobile : f.mp4)); expect(Math.abs(idle.duration - f.durationSec)).toBeLessThan(0.5); expect(idle.poster).toBe(f.poster.split('/').pop()); expect(idle.poster).toMatch(HASHED); expect(idle.posterLoaded).toBe(true); expect(idle.dur).toBe(f.durationLabel); expect(idle.title).toBe(f.title[lang]); expect(idle.figDir).toBe(lang === 'ar' ? 'rtl' : 'ltr');
    expect(idle.tracks).toEqual(['en:' + f.captions.en.split('/').pop() + (lang === 'en' ? ':default' : ''), 'ar:' + f.captions.ar.split('/').pop() + (lang === 'ar' ? ':default' : '')]); for (const t of idle.tracks) expect(t.split(':')[1]).toMatch(HASHED);
    expect(idle.name && idle.name.trim().length).toBeGreaterThan(3); expect(idle.role && idle.role.trim().length).toBeGreaterThan(3);
    expect(playing.paused).toBe(false); expect(playing.currentTime).toBeGreaterThan(2.5); expect(playing.src).toBe(want); expect(playing.showing).toHaveLength(1); expect(playing.showing[0].split(':')[0]).toBe(lang); expect(Number(playing.showing[0].split(':')[1])).toBeGreaterThanOrEqual(10); expect(playing.controls).toBe(true);
    if (tiles) { expect(tiles).toHaveLength(6); expect(tiles[0]).toMatch(/^40/); expect(tiles[5]).toMatch(/^45/); for (let i = 0; i < 6; i++) expect(tiles[i]).toMatch(new RegExp('^' + (40 + i))); }
    expect(page.__errors).toEqual([]); expect(page.__net).toEqual([]);
  });

  test('served: 30 hashed film files 200 + sha256 + immutable; no-store on /, index.html, build-info.json, js/exec-films.js (Cache-Control: no-cache request); build-info commit == deployed HEAD, version 1.7.0; 24 retired paths 404; ?v=1.7.0 on every served bundle tag', async ({ page }) => {
    test.setTimeout(300000); const rows = [];
    for (const id of FILM_ORDER) for (const [key, rel, sha] of FILES(FILMS.films[id])) { const r = await page.request.get(BASE + F(rel) + cb(), { headers: NO_CACHE, timeout: 180000 }); const body = await r.body(); const got = sha256(body); const cc = r.headers()['cache-control'] || ''; rows.push({ id, key, url: F(rel), status: r.status(), bytes: body.length, sha256: got, cacheControl: cc }); expect(r.status(), id + '.' + key).toBe(200); expect(got, id + '.' + key).toBe(sha); expect(cc, id + '.' + key).toContain('immutable'); }
    const noStore = [];
    for (const p of ['/', '/index.html', '/build-info.json', '/js/exec-films.js']) { const r = await page.request.get(BASE + p + cb(), { headers: NO_CACHE }); const cc = r.headers()['cache-control'] || ''; noStore.push({ url: p, status: r.status(), cacheControl: cc }); expect(r.status(), p).toBe(200); expect(cc, p).toBe('no-store'); }
    const info = await (await page.request.get(BASE + '/build-info.json' + cb(), { headers: NO_CACHE })).json(); rows.push({ servedCommit: info.commit, expectCommit: EXPECT_COMMIT, servedVersion: info.version, builtAt: info.builtAt, films: info.films }); expect(info.version).toBe(V); expect((info.commit || '').toLowerCase()).toBe(EXPECT_COMMIT); expect(info.films.map((f) => f.id)).toEqual(FILM_ORDER); for (const f of info.films) { const j = FILMS.films[f.id]; expect(f.status, f.id).toBe('shipped'); expect(f.file, f.id).toBe(F(j.mp4)); expect(f.sha256, f.id).toBe(j.mp4Sha256); expect(f.durationSec, f.id).toBe(j.durationSec); }
    const retired = []; for (const p of RETIRED) { const r = await page.request.get(BASE + p + cb(), { headers: NO_CACHE }); retired.push({ url: p, status: r.status() }); expect(r.status(), p).toBe(404); } expect(retired).toHaveLength(24);
    const html = await (await page.request.get(BASE + '/index.html' + cb(), { headers: NO_CACHE })).text(); const stamps = [...html.matchAll(/\?v=([0-9.]+)/g)].map((m) => m[1]); expect(stamps.length).toBeGreaterThanOrEqual(24); expect([...new Set(stamps)]).toEqual([V]); expect(html).toContain(`data-deck-version="${V}"`);
    const ef = await (await page.request.get(BASE + '/js/exec-films.js' + cb(), { headers: NO_CACHE })).text(); for (const id of FILM_ORDER) for (const [, rel] of FILES(FILMS.films[id])) expect(ef, rel).toContain(F(rel)); for (const p of RETIRED) expect(ef).not.toContain(p);
    write('served-' + test.info().project.name, [{ files: rows, noStore, retired, stamps: stamps.length }]);
  });

  test('deep links 32, 38, 39–45 (EN + AR) and all 45 slides EN + AR with 0 console errors and 0 failed requests; RTL in AR', async ({ page }) => {
    test.setTimeout(300000); await setup(page, 'en'); await open(page, 1); const dirs = {};
    for (const lang of ['en', 'ar']) { if (lang === 'ar') { await page.click('[data-testid="lang-toggle"]'); await page.waitForFunction(() => document.documentElement.dir === 'rtl', null, { timeout: 8000 }); } for (let n = 1; n <= 45; n++) { await page.evaluate((h) => { location.hash = h; }, hashFor(n)); await page.waitForFunction((n) => window.__qaVisible().n === n, n, { timeout: 9000 }); } dirs[lang] = await page.evaluate(() => document.documentElement.dir); }
    const deep = [];
    for (const lang of ['en', 'ar']) for (const n of [32, 38, 39, 40, 41, 42, 43, 44, 45]) { const ctx = await page.context().browser().newContext({ viewport: page.viewportSize() }); const p2 = await ctx.newPage(); await setup(p2, lang); await p2.goto(BASE + '/?lang=' + lang + hashFor(n), { waitUntil: 'load' }); await p2.waitForFunction(() => !!window.AtharGuide, null, { timeout: 20000 }); await p2.waitForFunction((n) => window.__qaVisible().n === n, n, { timeout: 15000 }); const got = await p2.evaluate(() => ({ n: window.__qaVisible().n, id: window.__qaVisible().id || null, dir: document.documentElement.dir, badge: document.querySelector('[data-testid="deck-version"]').textContent })); deep.push({ lang, n, hash: hashFor(n), ...got, errors: p2.__errors.length, failed: p2.__net.length }); expect(got.n, lang + ' ' + hashFor(n)).toBe(n); expect(got.badge).toBe('v' + V); expect(got.dir).toBe(lang === 'ar' ? 'rtl' : 'ltr'); expect(p2.__errors, 'deep link ' + n).toEqual([]); expect(p2.__net, 'deep link ' + n).toEqual([]); await ctx.close(); }
    write('sweep-' + test.info().project.name, [{ dirs, errors: page.__errors, failedRequests: page.__net, deep }]); expect(dirs).toEqual({ en: 'ltr', ar: 'rtl' }); expect(page.__errors).toEqual([]); expect(page.__net).toEqual([]);
  });
});
