// Athar deck v1.7.1 suite — RE-BASED in v1.7.2 on the re-cut section 10 (the v1.7.1 layout 46 Typography · 47 Brand assets · 48 Product assets no longer exists); identical checks to qa/v172 so the older suite keeps passing against the current deck. Section 10 "Brand" suite (46 Brand foundations · 47 Typography · 48 Product & asset gallery).
// (1) release metadata: every version literal == package.json; narration table 48 rows with 46/47/48 carrying EN + AR Scribe-verified clips (NAR-s50 · NAR-s52 · NAR-s51);
//     features/brand/assets.json: 47 content-hashed items (8 logo · 1 mood · 31 gallery = 9 sets × 1x/2x WebP + JPEG [+ 4 × 2x PNG] · 7 fonts incl. IBM Plex Sans Medium +
//     IBM Plex Sans Arabic Medium) all present under features/ and dist/ and listed in SHA256SUMS, four OFL licence texts; the colour system in dist/js/brand-data.js is
//     the v1.0 token set + moodboard accents looked up BY NAME in features/brand/brand-tokens.json (so slide 46 HEX == token file); no HEX literal in the runtime JS/CSS;
//     no .pdf / .docx under dist/ and no served text file links one (the guidelines are INTERNAL ONLY); CHANGELOG / RELEASE_NOTES / ledger carry the release;
// (2) slides 46–48 × EN/AR (cache-disabled context, 1440x900 + 390x844): active with data-n 46/47/48, counter 'n of 48', footer v<version>, dir follows the language,
//     kicker 'Section 10 · Brand' / 'القسم ١٠ · الهوية'; 46: EN lockup + أثر mark + reversed, clear-space diagram, minimum sizes, five token swatches whose data-hex and visible
//     <code> equal the token file (Sovereign Navy · Sand Off-White · Heritage Gold · Trace Cyan · Charcoal Ink), two moodboard accents (Emerald · Sand), three tone lines;
//     47: document.fonts.check true for '500 16px "IBM Plex Sans"' AND '500 16px "IBM Plex Sans Arabic"' (or the PENDING BRAND PACK fallback note), specimen incl. the Medium
//     pairing row, type system / scale tables, do + don't; 48: 11 tiles (persona board + 10) with source pills, six slide-38 'CONCEPT RENDER' tags (.aos-tag), the composited
//     renders flagged data-logo-composite 6 / 1 / 1, six personas EN+AR, four states, 1x/2x WebP + JPEG <picture>s, lightbox (Popover top layer, Esc closes without opening the overview);
//     0 console errors / 0 failed requests; screenshots per slide + the Section 09→10 overview with the SHOT_PREFIX label; the AR deck resolves the Arabic clip ids;
// (3) served: every brand image + font 200 + sha256 + immutable; brand-data.js / brand-fonts.css / brand-section.js / build-info.json no-store; build-info commit == EXPECT_COMMIT and
//     version == package.json; guideline file names 404; the six section-10 mp3 clips 200 + sha256;
// (4) deep links 32, 38, 39–45 unchanged + 46–48 via the canonical #/28/brand-k AND the #/29/brand-k alias AND #slide-46…48 (EN + AR); all 48 slides EN + AR with 0 console
//     errors / 0 failed requests; keyboard hand-over 45 → 46 → 45; next chevron disabled on 48.
// Usage: GUIDE_BASE=https://host EXPECT_COMMIT=<sha> SHOT_PREFIX=after SHOTS_DIR=/path PW_WORKERS=2 node ../../node_modules/@playwright/test/cli.js test -c playwright.config.mjs
import { test, expect } from '../../node_modules/@playwright/test/index.mjs';
import fs from 'node:fs'; import path from 'node:path'; import crypto from 'node:crypto'; import { execSync } from 'node:child_process';
import { instrument, FILE2CLIP, hashFor } from '../v154/lib.mjs';
const HERE = path.dirname(new URL(import.meta.url).pathname); const ROOT = path.join(HERE, '../..'); const BASE = process.env.GUIDE_BASE || 'http://127.0.0.1:4172'; const PREFIX = process.env.SHOT_PREFIX || 'after'; const SHOTS = process.env.SHOTS_DIR || path.join(HERE, 'screenshots');
const RESULTS = path.join(HERE, 'results'); fs.mkdirSync(RESULTS, { recursive: true }); fs.mkdirSync(SHOTS, { recursive: true });
const read = (rel) => fs.readFileSync(path.join(ROOT, rel), 'utf8'); const sha256 = (buf) => crypto.createHash('sha256').update(buf).digest('hex');
const PKG = JSON.parse(read('package.json')); const V = PKG.version; const FEAT = JSON.parse(read('features.json')); const FILMS = JSON.parse(read('features/exec-films/films.json'));
const BRAND = JSON.parse(read('features/brand/brand.json')); const TOK = JSON.parse(read('features/brand/brand-tokens.json')); const ASSETS = JSON.parse(read('features/brand/assets.json'));
const TABLE = JSON.parse(read('dist/narration/slide-narration.json')); const MANIFEST = JSON.parse(read('dist/narration/narration-manifest.json'));
const EXPECT_COMMIT = (process.env.EXPECT_COMMIT || execSync('git rev-parse HEAD', { cwd: HERE }).toString().trim()).toLowerCase(); const NO_CACHE = { 'Cache-Control': 'no-cache', Pragma: 'no-cache' }; const cb = () => '?cb=' + Date.now();
const SLIDES = [[46, 's-brand-foundations', 1, 'NAR-s50'], [47, 's-brand-typography', 2, 'NAR-s52'], [48, 's-brand-gallery', 3, 'NAR-s51']];
const HASHED = /\.([0-9a-f]{10})\.(png|jpg|webp|woff2)$/;
const byName = (arr, n) => { const h = arr.find((t) => t.name === n); if (!h) throw new Error('token missing: ' + n); return h.hex; };
const TOKEN_HEX = BRAND.colourSystem.tokens.map((t) => byName(TOK.superseded, t.token)); const ACCENT_HEX = BRAND.colourSystem.accents.map((a) => byName(TOK.palette, a.name));
const GUIDE_NAMES = ['Athar_Brand_Guidelines_FINAL.pdf', 'Athar_Brand_Guidelines_FINAL_v3.pdf', 'Athar_Brand_Guidelines_FINAL.docx', 'Athar_Brand_Guidelines.pdf'];
const write = (n, rows) => fs.writeFileSync(path.join(RESULTS, n + '.json'), JSON.stringify({ base: BASE, version: V, expectCommit: EXPECT_COMMIT, written: new Date().toISOString(), rows }, null, 1));
const vp = (info) => (info.project.name === 'phone' ? '390x844' : '1440x900');
async function setup(page, lang) { await page.addInitScript(instrument(FILE2CLIP, 1)); await page.addInitScript(({ lang }) => { try { sessionStorage.setItem('athar-intro-v1.4.2', 'done'); localStorage.setItem('athar-pact-lang', lang); } catch (e) {} }, { lang }); page.__errors = []; page.__net = []; page.on('pageerror', (e) => page.__errors.push(String(e))); page.on('console', (m) => { if (m.type() === 'error') page.__errors.push(m.text()); }); page.on('requestfailed', (r) => { const f = r.failure(); if (!f || f.errorText !== 'net::ERR_ABORTED') page.__net.push(r.url()); }); page.on('response', (r) => { if (r.status() >= 400) page.__net.push(r.status() + ' ' + r.url()); }); }
async function open(page, n, lang, hash) { await page.goto(BASE + '/' + (lang ? '?lang=' + lang : '') + (hash || hashFor(n)), { waitUntil: 'load' }); await page.waitForFunction(() => !!window.AtharGuide, null, { timeout: 20000 }); await page.waitForFunction((n) => window.__qaVisible().n === n, n, { timeout: 15000 }); }
function walk(d, out = []) { for (const e of fs.readdirSync(d, { withFileTypes: true })) { const p = path.join(d, e.name); if (e.isDirectory()) walk(p, out); else out.push(p); } return out; }

test.describe(`v${V} section 10 Brand (qa/v171 re-based on the v1.7.2 section: 46 Foundations · 47 Typography · 48 Gallery)`, () => {
  test('release metadata: version everywhere, 48 narration rows (46–48 EN + AR, Scribe-verified), 47 hashed brand assets / 9 gallery sets / 7 fonts in SHA256SUMS, colour system == token file by name, no PDF/DOCX in dist', async () => {
    expect(FEAT.version).toBe(V); expect(FILMS.version).toBe(V); expect(BRAND.version).toBe(V); expect(TOK.version).toBe(V); expect(ASSETS.version).toBe(V); expect(TABLE.version).toBe(V); expect(MANIFEST.version.startsWith('v' + V)).toBe(true);
    for (const loc of ['en', 'ar']) expect(JSON.parse(read(`dist/locales/impact-tiers.${loc}.json`)).version).toBe(V);
    for (const js of ['api-licences', 'athar-os', 'cobrand', 'impact-tiers', 'video-player', 'exec-film-player', 'exec-team', 'intro-gate', 'narration', 'brand-section']) expect(read(`dist/js/${js}.js`), js).toContain(`var VERSION = 'v${V}'`);
    expect(read('dist/js/img-guard.js')).toContain(`version: 'v${V}'`); expect(read('dist/js/brand-data.js')).toContain(`"version":"${V}"`); expect(read('dist/assets/brand-section.css')).toContain('v' + V); expect(read('dist/assets/brand-fonts.css')).toContain('v' + V);
    const html = read('dist/index.html'); expect(html).toContain(`data-deck-version="${V}"`); expect(html).toContain(`<meta name="application-version" content="${V}" />`); expect(html).toContain(`'v${V}'`);
    const stamps = [...html.matchAll(/\?v=([0-9.]+)/g)].map((m) => m[1]); expect(stamps.length).toBeGreaterThanOrEqual(28); expect([...new Set(stamps)]).toEqual([V]);
    expect(html).toContain("/^#\\/29\\/brand-([1-3])$/"); expect(html.indexOf('/js/brand-section.js')).toBeLessThan(html.indexOf('/js/exec-team.js'));
    /* narration */
    const sums = read('SHA256SUMS.txt'); expect(TABLE.slides.map((x) => x.n)).toEqual(Array.from({ length: 48 }, (_, i) => i + 1)); const nar = [];
    for (const [n, id, , clip] of SLIDES) { const r = TABLE.slides.find((x) => x.n === n); expect(r.slideId, 'slide ' + n).toBe(id); expect(r.clipId).toBe(clip); expect(r.file).toBe('/audio/guide/slides/' + clip + '-' + id + '.mp3'); expect(r.ar && r.ar.file).toBe('/audio/guide/slides/' + clip + '-' + id + '.ar.mp3'); expect(r.ar.clipId).toBe(clip + '-ar');
      for (const e of [r, r.ar]) { const p = path.join(ROOT, 'dist', e.file); expect(fs.existsSync(p), e.file).toBe(true); expect(sha256(fs.readFileSync(p)), e.file).toBe(e.sha256); expect(sums).toContain(e.sha256 + '  ./dist' + e.file); expect(e.durationSec).toBeGreaterThan(15); expect(e.source.contentCheck).toContain('Scribe'); expect(e.cues.length).toBeGreaterThanOrEqual(3); expect(e.cues[e.cues.length - 1].end).toBeLessThanOrEqual(e.durationSec + 0.05); expect(e.text.length).toBeGreaterThan(100); }
      nar.push({ n, id, en: r.clipId, ar: r.ar.clipId, enSec: r.durationSec, arSec: r.ar.durationSec }); expect(MANIFEST.segments.filter((s) => s.slideId === id).map((s) => s.lang).sort()).toEqual(['ar', 'en']); }
    for (const gone of ['NAR-s48-s-brand-assets.mp3', 'NAR-s49-s-brand-product.mp3']) expect(fs.existsSync(path.join(ROOT, 'dist/audio/guide/slides', gone)), gone).toBe(false);
    /* brand assets */
    const rows = [];
    for (const it of ASSETS.items) { const src = path.join(ROOT, 'features/brand/assets', it.file), dst = path.join(ROOT, 'dist/assets/brand', it.file); expect(it.file, it.id).toMatch(HASHED); expect(it.file.match(HASHED)[1]).toBe(it.sha256.slice(0, 10)); expect(fs.existsSync(src), src).toBe(true); expect(fs.existsSync(dst), dst).toBe(true); expect(sha256(fs.readFileSync(dst)), it.file).toBe(it.sha256); expect(sums, it.file).toContain(it.sha256 + '  ./dist/assets/brand/' + it.file); rows.push({ id: it.id, file: it.file, bytes: it.bytes, label: it.label || null, setId: it.setId || null, role: it.role || null }); }
    expect(rows).toHaveLength(47); const g = (grp) => ASSETS.items.filter((i) => i.group === grp).length; expect(g('logo')).toBe(8); expect(g('mood')).toBe(1); expect(g('gallery')).toBe(31); expect(g('fonts')).toBe(7);
    const sets = {}; for (const it of ASSETS.items) if (it.setId) (sets[it.setId] = sets[it.setId] || new Set()).add(it.role); expect(Object.keys(sets)).toHaveLength(9); for (const [k, s] of Object.entries(sets)) { expect([...s], k).toEqual(expect.arrayContaining(['webp1x', 'webp2x', 'jpg'])); } expect(Object.values(sets).filter((s) => s.has('png2x'))).toHaveLength(4);
    const fontIds = ASSETS.items.filter((i) => i.group === 'fonts').map((i) => i.id); expect(fontIds).toEqual(expect.arrayContaining(['IBMPlexSans-Medium', 'IBMPlexSansArabic-Medium', 'CormorantGaramond-Light', 'IBMPlexMono-Regular', 'IBMPlexSansArabic-Light']));
    for (const lic of ['OFL-cormorantgaramond.txt', 'OFL-ibmplexmono.txt', 'OFL-ibmplexsansarabic.txt', 'OFL-ibmplexsans.txt']) expect(fs.existsSync(path.join(ROOT, 'dist/assets/brand/fonts', lic)), lic).toBe(true);
    expect(ASSETS.logoGeometry.letters).toBe(5); expect(ASSETS.logoGeometry.inkMatchesDeepOcean).toBe(true);
    const comp = Object.fromEntries(ASSETS.items.filter((i) => i.role === 'jpg' && i.logoComposite).map((i) => [i.setId, i.logoComposite.placements.length])); expect(comp).toEqual({ 'render-stationery-flat-lay': 6, 'render-reception-kiosk': 1, 'render-laptop-phone-dashboard': 1 });
    /* colour system == token file (by name) and no HEX literal in the runtime */
    const data = JSON.parse(read('dist/js/brand-data.js').replace(/^[\s\S]*?window\.AtharBrandData = /, '').replace(/;\s*$/, ''));
    expect(data.colourSystem.tokens.map((t) => t.hex)).toEqual(TOKEN_HEX); expect(data.colourSystem.accents.map((a) => a.hex)).toEqual(ACCENT_HEX); expect(data.colourSystem.tokens.map((t) => t.token)).toEqual(['Sovereign Navy', 'Sand Off-White', 'Heritage Gold', 'Trace Cyan', 'Charcoal Ink']); expect(data.colourSystem.toneLines.map((t) => t.en)).toEqual(['Intelligence for a brighter tomorrow', 'People · Places · Progress', 'A more lasting impact']);
    expect(Object.keys(data.sets)).toHaveLength(9); expect(data.fonts.primary.en.stack).toContain('"IBM Plex Sans"'); expect(data.fonts.primary.ar.stack).toContain('"IBM Plex Sans Arabic"'); expect(data.personas.list).toHaveLength(6); expect(data.personas.states).toHaveLength(4);
    expect(read('dist/js/brand-section.js')).not.toMatch(/#[0-9A-Fa-f]{6}\b/); expect(read('dist/assets/brand-section.css')).not.toMatch(/#[0-9A-Fa-f]{6}\b/); expect(read('dist/assets/brand-fonts.css')).toContain('--brand-font-en:');
    /* confidentiality */
    const files = walk(path.join(ROOT, 'dist')); expect(files.filter((f) => /\.(pdf|docx)$/i.test(f))).toEqual([]);
    for (const f of files.filter((f) => /\.(html|js|css|json|txt|webmanifest)$/i.test(f))) { const t = fs.readFileSync(f, 'utf8'); expect(t, f).not.toMatch(/(href|src)=["'][^"']+\.(pdf|docx)["']/i); expect(t, f).not.toMatch(/url\([^)]+\.(pdf|docx)\)/i); }
    const cl = read('CHANGELOG.md'), rn = read('RELEASE_NOTES.md'); expect(cl).toContain('## v' + V); expect(rn).toContain('v' + V); expect(fs.existsSync(path.join(ROOT, 'asset-ledger-v' + V + '.csv'))).toBe(true); expect(read('features/brand/README.md')).toContain('PENDING BRAND PACK');
    write('release-metadata', [{ version: V, stamps: stamps.length, assets: rows, narration: nar, tokenHex: TOKEN_HEX, accentHex: ACCENT_HEX, composites: comp, distFiles: files.length }]);
  });

  for (const lang of ['en', 'ar']) for (const [n, id, k, clip] of SLIDES) test(`slide ${n} ${id} ${lang.toUpperCase()} (cache disabled): active, counter ${n} of 48, ${k === 1 ? 'lockups + colour system == tokens + tone lines' : k === 2 ? 'both brand font families loaded (document.fonts.check) + specimen' : '11 gallery tiles, concept tags, personas, lightbox'}; screenshot`, async ({ page }, info) => {
    test.setTimeout(240000); const mobile = info.project.name === 'phone';
    const cdp = await page.context().newCDPSession(page); await cdp.send('Network.enable'); await cdp.send('Network.setCacheDisabled', { cacheDisabled: true }); await setup(page, lang); await open(page, n, lang); await page.waitForTimeout(1200);
    const r = await page.evaluate(async ({ id, n }) => { const sec = document.getElementById(id); const q = (s) => sec.querySelector(s); const qa = (s) => [...sec.querySelectorAll(s)];
      let fonts = null; try { if (document.fonts && document.fonts.ready) { await document.fonts.ready; fonts = { sansMedium: document.fonts.check('500 16px "IBM Plex Sans"'), arabicMedium: document.fonts.check('500 16px "IBM Plex Sans Arabic"'), cormorant: document.fonts.check('300 16px "Cormorant Garamond"'), mono: document.fonts.check('400 16px "IBM Plex Mono"'), arabicLight: document.fonts.check('300 16px "IBM Plex Sans Arabic"') }; } } catch (e) {}
      const imgs = qa('img'); const broken = imgs.filter((i) => i.complete && i.naturalWidth === 0).map((i) => i.currentSrc || i.src);
      return { active: sec.classList.contains('is-active'), dataN: sec.getAttribute('data-n'), slideId: sec.getAttribute('data-slide-id'), visibleN: window.__qaVisible().n, dir: document.documentElement.dir, lang: document.documentElement.lang, hash: location.hash,
        counter: (document.querySelector('footer.pagefooter .counter') || {}).textContent, badge: (document.querySelector('[data-testid="deck-version"]') || {}).textContent, html: document.documentElement.getAttribute('data-deck-version'), kicker: (q('.s-kicker') || {}).textContent, h2: (q('.s-head h2') || {}).textContent,
        total: window.AtharBrand && window.AtharBrand.total(), execTotal: window.AtharExecTeam && window.AtharExecTeam.total, itTotal: window.AtharImpactTiers && window.AtharImpactTiers.total, current: window.AtharImpactTiers && window.AtharImpactTiers.current(),
        fontsAttr: sec.getAttribute('data-fonts'), fontsPrimary: sec.getAttribute('data-fonts-primary'), fontsState: (q('[data-testid="brand-fonts-state"]') || {}).textContent || null, fonts, stacks: (q('[data-testid="brand-font-stacks"]') || {}).textContent || null,
        specimenRows: qa('.br-spec-row').length, mediumRow: !!q('.br-t-medium'), systemRows: qa('[data-testid="brand-type-system"] tr').length, scaleRows: qa('[data-testid="brand-type-scale"] tr').length, dos: qa('.br-do li').length, donts: qa('.br-dont li').length,
        swatches: qa('[data-testid="brand-swatch"]').map((s) => s.getAttribute('data-hex')), swatchText: qa('[data-testid="brand-swatch-hex"]').map((c) => c.textContent), swatchBg: qa('[data-testid="brand-swatch"] .br-swatch-chip').map((c) => getComputedStyle(c).backgroundColor), swatchNames: qa('[data-testid="brand-swatch"] .br-swatch-name').map((c) => c.textContent), accents: qa('[data-testid="brand-accent-swatch"]').map((s) => s.getAttribute('data-hex')), tone: qa('.br-tone-line').map((t) => t.textContent.trim().slice(0, 40)),
        lockups: ['brand-lockup-en', 'brand-lockup-mark', 'brand-lockup-reversed'].map((t) => !!q('[data-testid="' + t + '"] img')), clear: !!q('[data-testid="brand-clear-space"]'), clearX: q('[data-testid="brand-clear-space"] .br-clear-box') ? q('[data-testid="brand-clear-space"] .br-clear-box').style.getPropertyValue('--br-x') : null, minRows: qa('[data-testid="brand-min-sizes"] tr').length,
        tiles: qa('[data-testid="brand-product-tile"]').map((t) => t.getAttribute('data-asset') + ':' + t.getAttribute('data-label') + ':' + (t.getAttribute('data-logo-composite') || '')), concept: qa('[data-testid="concept-tag"]').map((t) => t.textContent), pictures: qa('[data-testid="brand-product-tile"] picture source[type="image/webp"]').map((s) => s.srcset).filter((s) => / 1x, .* 2x$/.test(s) || / \d+w, .* \d+w$/.test(s)).length, jpgFallbacks: qa('[data-testid="brand-product-tile"] picture img').filter((i) => /\.(jpg|webp)$/.test(i.getAttribute('src'))).length,
        personas: qa('.br-persona').map((p) => p.querySelector('.br-persona-en').textContent + '/' + p.querySelector('.br-persona-ar').textContent), states: qa('.br-state').map((s) => s.getAttribute('data-state')), sizes: qa('.br-size-dot').length,
        backdrop: (q('.br-backdrop') ? getComputedStyle(q('.br-backdrop')).backgroundImage : '').includes('render-brand-background-tile'), imgs: imgs.length, broken, overflowX: sec.scrollWidth > sec.clientWidth + 2, clipId: window.AtharGuide && window.AtharGuide.clipFor ? window.AtharGuide.clipFor(id) : null, railOrder: [...document.querySelectorAll('nav.rail ol li')].map((li) => (li.querySelector('.rail-n') || {}).textContent).join(','), railCurrent: (document.querySelector('nav.rail li.is-current .rail-n') || {}).textContent, railTxt: (document.querySelector('nav.rail li[data-brand-chapter] a') || {}).textContent, nextDisabled: document.querySelector('button.arrow.next').disabled }; }, { id, n });
    await page.screenshot({ path: path.join(SHOTS, `${PREFIX}-slide-${n}-${lang}-${vp(info)}.png`) });
    let lightbox = null; if (k === 3) { await page.click('[data-testid="brand-product-tile"][data-asset="render-reception-kiosk"]'); await page.waitForSelector('[data-testid="brand-lightbox"]', { timeout: 8000 }); await page.waitForTimeout(300); lightbox = await page.evaluate(() => { const f = document.querySelector('[data-testid="brand-lightbox"]'); const rc = f.getBoundingClientRect(); return { open: true, popover: f.hasAttribute('popover'), role: f.getAttribute('role'), modal: f.getAttribute('aria-modal'), img: (f.querySelector('img') || {}).currentSrc || null, w: Math.round(rc.width), h: Math.round(rc.height), bodyFlag: document.body.classList.contains('br-lightbox-open') }; }); await page.screenshot({ path: path.join(SHOTS, `${PREFIX}-slide-48-lightbox-${lang}-${vp(info)}.png`) }); await page.keyboard.press('Escape'); await page.waitForTimeout(300); Object.assign(lightbox, await page.evaluate(() => ({ closed: !document.querySelector('[data-testid="brand-lightbox"]'), overviewOpened: !!document.querySelector('.overview'), hash: location.hash }))); }
    let tiles = null; if (k === 3) { await page.click('[data-testid="overview-toggle"]'); await page.waitForSelector('[data-testid="overview"] button.ov-card[data-brand]', { timeout: 10000 }); await page.waitForTimeout(500); tiles = await page.evaluate(() => ({ brand: [...document.querySelectorAll('[data-testid="overview"] button.ov-card[data-brand]')].map((b) => b.textContent.trim()), exec: [...document.querySelectorAll('[data-testid="overview"] button.ov-card[data-exec]')].map((b) => b.textContent.trim()), total: document.querySelectorAll('[data-testid="overview"] button.ov-card').length, on: (document.querySelector('[data-testid="overview"] button.ov-card.on') || {}).textContent })); await page.evaluate(() => { const b = document.querySelector('[data-testid="overview"] button.ov-card[data-exec="1"]'); if (b) b.scrollIntoView({ block: 'center' }); }); await page.waitForTimeout(300); await page.screenshot({ path: path.join(SHOTS, `${PREFIX}-section10-overview-${lang}-${vp(info)}.png`) }); }
    write(`slide-${n}-${lang}-` + info.project.name, [{ ...r, lightbox, tiles, errors: page.__errors, failedRequests: page.__net }]);
    expect(r.active).toBe(true); expect(r.dataN).toBe(String(n)); expect(r.slideId).toBe(id); expect(r.visibleN).toBe(n); expect(r.lang).toBe(lang); expect(r.dir).toBe(lang === 'ar' ? 'rtl' : 'ltr'); expect(r.hash).toBe(hashFor(n)); /* v1.7.3: #/29/brand-k alias in the address bar */
    expect(r.counter).toContain(String(n)); expect(r.counter).toContain('48'); expect(r.badge).toBe('v' + V); expect(r.html).toBe(V); expect(r.total).toBe(48); expect(r.execTotal).toBe(48); expect(r.itTotal).toBe(48); expect(r.current).toBe(n);
    expect(r.kicker).toContain(lang === 'ar' ? 'القسم ١٠ · الهوية' : 'Section 10 · Brand'); expect(r.railTxt).toBe('10' + (lang === 'ar' ? 'الهوية' : 'Brand')); expect(r.railOrder).toBe('01,02,03,04,05,06,07,08,09,10'); expect(r.railCurrent).toBe('10'); expect(r.h2 && r.h2.length).toBeGreaterThan(3); expect(r.broken).toEqual([]); expect(r.overflowX).toBe(false); expect(r.backdrop).toBe(true);
    expect(r.clipId).toBe(clip + (lang === 'ar' ? '-ar' : '')); expect(r.nextDisabled).toBe(k === 3); expect(['loaded', 'fallback']).toContain(r.fontsPrimary);
    if (k === 1) { expect(r.lockups).toEqual([true, true, true]); expect(r.clear).toBe(true); expect(r.clearX).toContain('%'); expect(r.minRows).toBe(5); expect(r.swatches).toEqual(TOKEN_HEX); expect(r.swatchText).toEqual(TOKEN_HEX); const rgb = (h) => 'rgb(' + [1, 3, 5].map((i) => parseInt(h.slice(i, i + 2), 16)).join(', ') + ')'; expect(r.swatchBg).toEqual(TOKEN_HEX.map(rgb)); expect(r.swatchNames).toEqual(['Sovereign Navy', 'Sand Off-White', 'Heritage Gold', 'Trace Cyan', 'Charcoal Ink']); expect(r.accents).toEqual(ACCENT_HEX); expect(r.tone).toHaveLength(3); }
    if (k === 2) { if (r.fontsPrimary === 'loaded') { expect(r.fonts.sansMedium, 'IBM Plex Sans 500').toBe(true); expect(r.fonts.arabicMedium, 'IBM Plex Sans Arabic 500').toBe(true); expect(r.fontsState).toContain('7/7'); } else expect(r.fontsState).toContain('PENDING BRAND PACK'); expect(r.stacks).toContain('Lucida Grande'); expect(r.stacks).toContain('Segoe UI'); expect(r.specimenRows).toBeGreaterThanOrEqual(6); expect(r.mediumRow).toBe(true); expect(r.systemRows).toBe(6); expect(r.scaleRows).toBe(8); expect(r.dos).toBeGreaterThanOrEqual(3); expect(r.donts).toBeGreaterThanOrEqual(3); }
    if (k === 3) { expect(r.tiles).toHaveLength(11); expect(r.tiles.filter((t) => t.includes(':PACK ASSET:'))).toHaveLength(5); expect(r.tiles.filter((t) => t.includes(':CONCEPT RENDER:'))).toHaveLength(6); expect(r.tiles).toEqual(expect.arrayContaining(['render-stationery-flat-lay:CONCEPT RENDER:6', 'render-reception-kiosk:CONCEPT RENDER:1', 'render-laptop-phone-dashboard:CONCEPT RENDER:1', '__india__:CONCEPT RENDER:', '__kenya__:CONCEPT RENDER:'])); expect(r.concept).toHaveLength(6); for (const t of r.concept) expect(t).toBe(lang === 'ar' ? 'تصوّر مفاهيمي' : 'CONCEPT RENDER'); expect(r.pictures).toBe(11); expect(r.personas).toEqual(['Guide/المرشد', 'Clerk/الكاتب', 'Scout/الكاشف', 'Tutor/المعلّم', 'Translator/المترجم', 'Steward/الأمين']); expect(r.states).toEqual(['Idle', 'Thinking', 'Awaiting Human Approval', 'Done']); expect(r.sizes).toBe(3); expect(r.imgs).toBeGreaterThanOrEqual(12);
      expect(lightbox.open).toBe(true); expect(lightbox.role).toBe('dialog'); expect(lightbox.modal).toBe('true'); expect(lightbox.img).toContain('/assets/brand/gallery/render-reception-kiosk'); expect(lightbox.w).toBeGreaterThanOrEqual(page.viewportSize().width - 2); expect(lightbox.closed).toBe(true); expect(lightbox.overviewOpened).toBe(false); expect(lightbox.hash).toBe(hashFor(48));
      expect(tiles.total).toBe(48); expect(tiles.brand.map((t) => t.slice(0, 2))).toEqual(['46', '47', '48']); expect(tiles.exec.map((t) => t.slice(0, 2))).toEqual(['40', '41', '42', '43', '44', '45']); expect(tiles.on).toMatch(/^48/); }
    expect(page.__errors).toEqual([]); expect(page.__net).toEqual([]);
  });

  test('served: 47 hashed brand files 200 + sha256 + immutable; brand-data.js / brand-fonts.css / brand-section.js / build-info.json no-store; build-info commit == deployed HEAD; six section-10 clips 200; guideline file names 404', async ({ page }) => {
    test.setTimeout(300000); const rows = [];
    for (const it of ASSETS.items) { const r = await page.request.get(BASE + ASSETS.distBase + it.file + cb(), { headers: NO_CACHE, timeout: 120000 }); const body = await r.body(); const cc = r.headers()['cache-control'] || ''; rows.push({ id: it.id, url: ASSETS.distBase + it.file, status: r.status(), bytes: body.length, sha256: sha256(body), cacheControl: cc, contentType: r.headers()['content-type'] }); expect(r.status(), it.file).toBe(200); expect(sha256(body), it.file).toBe(it.sha256); expect(cc, it.file).toContain('immutable'); }
    for (const pl of ['plate5-india-v161', 'plate5-kenya-v161']) for (const ext of ['-1x.webp', '-2x.webp', '-1x.jpg']) { const r = await page.request.get(BASE + '/assets/plates/' + pl + ext + cb(), { headers: NO_CACHE }); expect(r.status(), pl + ext).toBe(200); }
    const noStore = [];
    for (const p of ['/js/brand-data.js', '/js/brand-section.js', '/assets/brand-fonts.css', '/assets/brand-section.css', '/build-info.json', '/narration/slide-narration.json', '/index.html']) { const r = await page.request.get(BASE + p + cb(), { headers: NO_CACHE }); const cc = r.headers()['cache-control'] || ''; noStore.push({ url: p, status: r.status(), cacheControl: cc }); expect(r.status(), p).toBe(200); expect(cc, p).toBe('no-store'); }
    const info = await (await page.request.get(BASE + '/build-info.json' + cb(), { headers: NO_CACHE })).json(); expect(info.version).toBe(V); expect((info.commit || '').toLowerCase()).toBe(EXPECT_COMMIT);
    const served = await (await page.request.get(BASE + '/js/brand-data.js' + cb(), { headers: NO_CACHE })).text(); const data = JSON.parse(served.replace(/^[\s\S]*?window\.AtharBrandData = /, '').replace(/;\s*$/, '')); expect(data.colourSystem.tokens.map((t) => t.hex)).toEqual(TOKEN_HEX); expect(data.version).toBe(V);
    const forbidden = []; for (const name of GUIDE_NAMES) for (const dir of ['/', '/assets/brand/', '/assets/', '/features/brand/', '/brand/']) { const r = await page.request.get(BASE + dir + name + cb(), { headers: NO_CACHE }); forbidden.push({ url: dir + name, status: r.status() }); expect(r.status(), dir + name).toBe(404); }
    for (const p of ['/features/brand/brand-tokens.json', '/features/brand/assets.json', '/features/brand/brand-asset-manifest.csv']) { const r = await page.request.get(BASE + p + cb(), { headers: NO_CACHE }); expect(r.status(), p).toBe(404); }
    const html = await (await page.request.get(BASE + '/index.html' + cb(), { headers: NO_CACHE })).text(); const stamps = [...html.matchAll(/\?v=([0-9.]+)/g)].map((m) => m[1]); expect(stamps.length).toBeGreaterThanOrEqual(28); expect([...new Set(stamps)]).toEqual([V]);
    const clips = []; for (const e of TABLE.slides.filter((s) => s.n >= 46)) for (const f of [e.file, e.ar.file]) { const r = await page.request.get(BASE + f + cb(), { headers: NO_CACHE }); const body = await r.body(); clips.push({ file: f, status: r.status(), bytes: body.length }); expect(r.status(), f).toBe(200); expect(sha256(body), f).toBe(f === e.file ? e.sha256 : e.ar.sha256); } expect(clips).toHaveLength(6);
    write('served-' + test.info().project.name, [{ files: rows, noStore, forbidden, clips, servedCommit: info.commit, servedVersion: info.version, builtAt: info.builtAt, stamps: stamps.length }]);
  });

  test('deep links 32, 38, 39–45 unchanged + 46–48 via #/28/brand-k, the #/29/brand-k alias and #slide-46…48 (EN + AR); all 48 slides EN + AR with 0 console errors / 0 failed requests; keyboard 45 → 46 → 45; RTL in AR', async ({ page }) => {
    test.setTimeout(420000); await setup(page, 'en'); await open(page, 1); const dirs = {};
    for (const lang of ['en', 'ar']) { if (lang === 'ar') { await page.click('[data-testid="lang-toggle"]'); await page.waitForFunction(() => document.documentElement.dir === 'rtl', null, { timeout: 8000 }); } for (let n = 1; n <= 48; n++) { await page.evaluate((h) => { location.hash = h; }, hashFor(n)); await page.waitForFunction((n) => window.__qaVisible().n === n, n, { timeout: 9000 }); } dirs[lang] = await page.evaluate(() => document.documentElement.dir); }
    const deep = [];
    const targets = [32, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48].map((n) => [n, hashFor(n)]).concat([[46, '#/29/brand-1'], [47, '#/29/brand-2'], [48, '#/29/brand-3'], [46, '#slide-46'], [48, '#slide-48']]);
    for (const lang of ['en', 'ar']) for (const [n, h] of targets) { const ctx = await page.context().browser().newContext({ viewport: page.viewportSize() }); const p2 = await ctx.newPage(); await setup(p2, lang); await p2.goto(BASE + '/?lang=' + lang + h, { waitUntil: 'load' }); await p2.waitForFunction(() => !!window.AtharGuide, null, { timeout: 20000 }); await p2.waitForFunction((n) => window.__qaVisible().n === n, n, { timeout: 20000 }); const v = await p2.evaluate(() => ({ ...window.__qaVisible(), dir: document.documentElement.dir, hash: location.hash })); deep.push({ lang, n, requested: h, ...v, errors: p2.__errors, failed: p2.__net }); expect(v.n, lang + ' ' + h).toBe(n); expect(v.hash, lang + ' ' + h).toBe(hashFor(n)); expect(v.dir).toBe(lang === 'ar' ? 'rtl' : 'ltr'); expect(p2.__errors).toEqual([]); expect(p2.__net).toEqual([]); await ctx.close(); }
    const ctx = await page.context().browser().newContext({ viewport: page.viewportSize() }); const p3 = await ctx.newPage(); await setup(p3, 'en'); await open(p3, 45, 'en'); await p3.waitForTimeout(500);
    await p3.keyboard.press('ArrowRight'); await p3.waitForFunction(() => window.__qaVisible().n === 46, null, { timeout: 8000 }); const k1 = await p3.evaluate(() => ({ ...window.__qaVisible(), hash: location.hash, counter: document.querySelector('footer.pagefooter .counter').textContent }));
    await p3.keyboard.press('ArrowLeft'); await p3.waitForFunction(() => window.__qaVisible().n === 45, null, { timeout: 8000 }); const k2 = await p3.evaluate(() => ({ ...window.__qaVisible(), hash: location.hash }));
    write('sweep-' + test.info().project.name, [{ dirs, errors: page.__errors, failedRequests: page.__net, deep, keys: { k1, k2 } }]);
    expect(dirs).toEqual({ en: 'ltr', ar: 'rtl' }); expect(page.__errors).toEqual([]); expect(page.__net).toEqual([]); expect(k1.slideId).toBe('s-brand-foundations'); expect(k1.hash).toBe(hashFor(46)); expect(k1.counter).toContain('46'); expect(k2.slideId).toBe('s-exec-lorenzo'); expect(k2.hash).toBe('#/28/exec-6'); expect(p3.__errors).toEqual([]); await ctx.close();
  });
});
