// Athar deck v1.7.1 — section 10 "Branding" suite (slides 46 Typography · 47 Brand assets · 48 Product assets; deep links #/28/brand-1…3).
// (1) release metadata: package / features / films.json / brand feature files / every VERSION literal / narration table (48 rows, 46–48 with EN + AR clips) /
//     index.html stamps all read package.json's version; every features/brand asset is content-hashed with its own sha256 and listed in SHA256SUMS (+ its dist copy);
//     the palette HEX on the slide data (dist/js/brand-data.js) equals features/brand/brand-tokens.json (which is extracted from the guidelines, never typed);
//     no .pdf / .docx exists anywhere under dist/ (the brand guidelines are INTERNAL ONLY) and no served text file links one;
// (2) slides 46–48 × EN/AR (cache-disabled context, 1440x900 + 390x844): the section is active with data-n 46/47/48, counter 'n of 48', footer v<version>, dir follows the
//     language; slide 46 reports the self-hosted brand fonts loaded via document.fonts (or shows the PENDING BRAND PACK fallback note), slide 47's five swatches carry the
//     token HEX values (DOM data-hex + visible <code>), the light/dark token lists match brand-tokens.json, the lockups/clear-space/misuse/pack blocks exist, slide 48 has 10
//     tiles (9 assets + the India/Kenya/Lebanon triptych) each with a source pill (PACK ASSET / FILM STILL / CONCEPT RENDER); 0 console errors / 0 failed requests;
//     screenshots per slide (and the overview 40–48) with the SHOT_PREFIX label; the AR deck resolves the Arabic clip id (NAR-s4x-ar) for the three slides;
// (3) served: every new image + font 200 + sha256 + immutable; brand-data.js / brand-fonts.css / brand-section.js / build-info.json no-store; build-info commit == EXPECT_COMMIT and
//     version == package.json; guideline file names answer 404 at the root, under /assets/brand/ and under /features/;
// (4) deep links 32, 38, 39–45 unchanged + 46–48 land (EN + AR); all 48 slides EN + AR with 0 console errors / 0 failed requests; keyboard hand-over 45 → 46 → 45; next chevron disabled on 48.
// Usage: GUIDE_BASE=https://host EXPECT_COMMIT=<sha> SHOT_PREFIX=after SHOTS_DIR=/path PW_WORKERS=2 node ../../node_modules/@playwright/test/cli.js test -c playwright.config.mjs
import { test, expect } from '../../node_modules/@playwright/test/index.mjs';
import fs from 'node:fs'; import path from 'node:path'; import crypto from 'node:crypto'; import { execSync } from 'node:child_process';
import { instrument, FILE2CLIP, hashFor } from '../v154/lib.mjs';
const HERE = path.dirname(new URL(import.meta.url).pathname); const ROOT = path.join(HERE, '../..'); const BASE = process.env.GUIDE_BASE || 'http://127.0.0.1:4171'; const PREFIX = process.env.SHOT_PREFIX || 'after'; const SHOTS = process.env.SHOTS_DIR || path.join(HERE, 'screenshots');
const RESULTS = path.join(HERE, 'results'); fs.mkdirSync(RESULTS, { recursive: true }); fs.mkdirSync(SHOTS, { recursive: true });
const read = (rel) => fs.readFileSync(path.join(ROOT, rel), 'utf8'); const sha256 = (buf) => crypto.createHash('sha256').update(buf).digest('hex');
const PKG = JSON.parse(read('package.json')); const V = PKG.version; const FEAT = JSON.parse(read('features.json')); const FILMS = JSON.parse(read('features/exec-films/films.json'));
const BRAND = JSON.parse(read('features/brand/brand.json')); const TOK = JSON.parse(read('features/brand/brand-tokens.json')); const ASSETS = JSON.parse(read('features/brand/assets.json'));
const TABLE = JSON.parse(read('dist/narration/slide-narration.json')); const MANIFEST = JSON.parse(read('dist/narration/narration-manifest.json'));
const EXPECT_COMMIT = (process.env.EXPECT_COMMIT || execSync('git rev-parse HEAD', { cwd: HERE }).toString().trim()).toLowerCase(); const NO_CACHE = { 'Cache-Control': 'no-cache', Pragma: 'no-cache' }; const cb = () => '?cb=' + Date.now();
const SLIDES = [[46, 's-brand-typography', 1], [47, 's-brand-assets', 2], [48, 's-brand-product', 3]]; const IDS = SLIDES.map((s) => s[1]);
const HASHED = /\.([0-9a-f]{10})\.(png|jpg|webp|woff2)$/; const PALETTE = TOK.palette.map((p) => p.hex);
const GUIDE_NAMES = ['Athar_Brand_Guidelines_FINAL.pdf', 'Athar_Brand_Guidelines_FINAL.docx', 'Athar_Brand_Guidelines_FINAL_v3.pdf', 'Athar_Brand_Guidelines.pdf', 'Athar_Brand_Guidelines.docx'];
const write = (n, rows) => fs.writeFileSync(path.join(RESULTS, n + '.json'), JSON.stringify({ base: BASE, version: V, expectCommit: EXPECT_COMMIT, written: new Date().toISOString(), rows }, null, 1));
const vp = (info) => (info.project.name === 'phone' ? '390x844' : '1440x900');
async function setup(page, lang) { await page.addInitScript(instrument(FILE2CLIP, 1)); await page.addInitScript(({ lang }) => { try { sessionStorage.setItem('athar-intro-v1.4.2', 'done'); localStorage.setItem('athar-pact-lang', lang); } catch (e) {} }, { lang }); page.__errors = []; page.__net = []; page.on('pageerror', (e) => page.__errors.push(String(e))); page.on('console', (m) => { if (m.type() === 'error') page.__errors.push(m.text()); }); page.on('requestfailed', (r) => { const f = r.failure(); if (!f || f.errorText !== 'net::ERR_ABORTED') page.__net.push(r.url()); }); page.on('response', (r) => { if (r.status() >= 400) page.__net.push(r.status() + ' ' + r.url()); }); }
async function open(page, n, lang) { await page.goto(BASE + '/' + (lang ? '?lang=' + lang : '') + hashFor(n), { waitUntil: 'load' }); await page.waitForFunction(() => !!window.AtharGuide, null, { timeout: 20000 }); await page.waitForFunction((n) => window.__qaVisible().n === n, n, { timeout: 15000 }); }
function walk(d, out = []) { for (const e of fs.readdirSync(d, { withFileTypes: true })) { const p = path.join(d, e.name); if (e.isDirectory()) walk(p, out); else out.push(p); } return out; }

test.describe(`v${V} section 10 Branding`, () => {
  test('release metadata: version everywhere, 48 narration rows (46–48 EN + AR, Scribe-verified), 25 content-hashed brand assets in SHA256SUMS, palette HEX == brand-tokens.json, no PDF/DOCX in dist', async () => {
    expect(FEAT.version).toBe(V); expect(FILMS.version).toBe(V); expect(BRAND.version).toBe(V); expect(TOK.version).toBe(V); expect(ASSETS.version).toBe(V); expect(TABLE.version).toBe(V); expect(MANIFEST.version.startsWith('v' + V)).toBe(true);
    for (const loc of ['en', 'ar']) expect(JSON.parse(read(`dist/locales/impact-tiers.${loc}.json`)).version).toBe(V);
    for (const js of ['api-licences', 'athar-os', 'cobrand', 'impact-tiers', 'video-player', 'exec-film-player', 'exec-team', 'intro-gate', 'narration', 'brand-section']) expect(read(`dist/js/${js}.js`), js).toContain(`var VERSION = 'v${V}'`);
    expect(read('dist/js/img-guard.js')).toContain(`version: 'v${V}'`); expect(read('dist/js/brand-data.js')).toContain(`"version":"${V}"`); expect(read('dist/assets/brand-section.css')).toContain('v' + V); expect(read('dist/assets/brand-fonts.css')).toContain('v' + V);
    const html = read('dist/index.html'); expect(html).toContain(`data-deck-version="${V}"`); expect(html).toContain(`<meta name="application-version" content="${V}" />`); expect(html).toContain(`'v${V}'`);
    const stamps = [...html.matchAll(/\?v=([0-9.]+)/g)].map((m) => m[1]); expect(stamps.length).toBeGreaterThanOrEqual(28); expect([...new Set(stamps)]).toEqual([V]);
    for (const tag of ['/assets/brand-fonts.css', '/assets/brand-section.css', '/js/brand-data.js', '/js/brand-section.js']) expect(html).toContain(tag + '?v=' + V);
    expect(html.indexOf('/js/brand-section.js')).toBeLessThan(html.indexOf('/js/exec-team.js')); expect(html).toContain("n>45?'#/28/brand-'+(n-45)");
    /* narration table: 48 rows, 46–48 with EN file + ar{} clip, both Scribe-verified, files in SHA256SUMS */
    const sums = read('SHA256SUMS.txt'); expect(TABLE.slides.map((x) => x.n)).toEqual(Array.from({ length: 48 }, (_, i) => i + 1));
    const nar = [];
    for (const [n, id, k] of SLIDES) { const r = TABLE.slides.find((x) => x.n === n); expect(r.slideId, 'slide ' + n).toBe(id); expect(r.clipId).toBe('NAR-s' + (46 + k)); expect(r.file).toBe('/audio/guide/slides/NAR-s' + (46 + k) + '-' + id + '.mp3'); expect(r.ar && r.ar.file).toBe('/audio/guide/slides/NAR-s' + (46 + k) + '-' + id + '.ar.mp3'); expect(r.ar.clipId).toBe(r.clipId + '-ar');
      for (const e of [r, r.ar]) { const p = path.join(ROOT, 'dist', e.file); expect(fs.existsSync(p), e.file).toBe(true); expect(sha256(fs.readFileSync(p)), e.file).toBe(e.sha256); expect(sums).toContain(e.sha256 + '  ./dist' + e.file); expect(e.durationSec).toBeGreaterThan(15); expect(e.source.contentCheck).toContain('Scribe'); expect(e.cues.length).toBeGreaterThanOrEqual(3); expect(e.cues[e.cues.length - 1].end).toBeLessThanOrEqual(e.durationSec + 0.05); expect(e.text.length).toBeGreaterThan(100); }
      nar.push({ n, id, en: r.clipId, ar: r.ar.clipId, enSec: r.durationSec, arSec: r.ar.durationSec }); expect(MANIFEST.segments.filter((s) => s.slideId === id).map((s) => s.lang).sort()).toEqual(['ar', 'en']); }
    /* brand assets: every item content-hashed with its own sha256, present under features/ and dist/, listed in SHA256SUMS; fonts + licences */
    const rows = [];
    for (const it of ASSETS.items) { const src = path.join(ROOT, 'features/brand/assets', it.file), dst = path.join(ROOT, 'dist/assets/brand', it.file); expect(it.file, it.id).toMatch(HASHED); expect(it.file.match(HASHED)[1]).toBe(it.sha256.slice(0, 10)); expect(fs.existsSync(src), src).toBe(true); expect(fs.existsSync(dst), dst).toBe(true); expect(sha256(fs.readFileSync(dst)), it.file).toBe(it.sha256); expect(sums, it.file).toContain(it.sha256 + '  ./dist/assets/brand/' + it.file); rows.push({ id: it.id, file: it.file, bytes: it.bytes, label: it.label || null }); }
    expect(rows).toHaveLength(25); expect(ASSETS.items.filter((i) => i.group === 'fonts')).toHaveLength(5); expect(ASSETS.items.filter((i) => i.group === 'logo')).toHaveLength(8); expect(ASSETS.items.filter((i) => i.group === 'product')).toHaveLength(9); expect(ASSETS.items.filter((i) => i.group === 'mood')).toHaveLength(3);
    for (const lic of ['OFL-cormorantgaramond.txt', 'OFL-ibmplexmono.txt', 'OFL-ibmplexsansarabic.txt']) expect(fs.existsSync(path.join(ROOT, 'dist/assets/brand/fonts', lic)), lic).toBe(true);
    expect(ASSETS.logoGeometry.letters).toBe(5); expect(ASSETS.logoGeometry.inkMatchesDeepOcean).toBe(true); expect(ASSETS.logoGeometry.inkHex).toBe(PALETTE[0]);
    const mood = ASSETS.items.find((i) => i.id === 'athar-mood-board-key-visual'); for (const [name, c] of Object.entries(mood.swatchCheck)) expect(c.absDiff, name).toBeLessThanOrEqual(3);
    /* palette: the generated data module carries exactly the token file's HEX values; no HEX literal in the runtime JS/CSS */
    const data = JSON.parse(read('dist/js/brand-data.js').replace(/^[\s\S]*?window\.AtharBrandData = /, '').replace(/;\s*$/, ''));
    expect(data.tokens.palette.map((p) => p.hex)).toEqual(PALETTE); expect(data.tokens.light).toEqual(TOK.light); expect(data.tokens.dark).toEqual(TOK.dark); expect(PALETTE).toHaveLength(5); expect(TOK.light.length).toBeGreaterThanOrEqual(30); expect(TOK.dark.length).toBeGreaterThanOrEqual(30); expect(TOK.source.method).toContain('extract_brand_tokens.py');
    expect(read('dist/js/brand-section.js')).not.toMatch(/#[0-9A-Fa-f]{6}\b/); expect(read('dist/assets/brand-section.css')).not.toMatch(/#[0-9A-Fa-f]{6}\b/);
    expect(data.pack.manifestCounts.rows).toBe(96); expect(data.pack.manifestCounts.byFileType.reduce((a, r) => a + r.n, 0)).toBe(96); expect(data.pack.name).toBe('Athar_Brand_Asset_Pack_v3'); expect(data.pack.storage).toBe('Google Drive / SharePoint'); expect(data.pack.pending.length).toBeGreaterThanOrEqual(3);
    /* confidentiality: no PDF / DOCX under dist/, none referenced by any served text file */
    const files = walk(path.join(ROOT, 'dist')); const docs = files.filter((f) => /\.(pdf|docx)$/i.test(f)); expect(docs).toEqual([]);
    for (const f of files.filter((f) => /\.(html|js|css|json|txt|webmanifest)$/i.test(f))) { const t = fs.readFileSync(f, 'utf8'); expect(t, f).not.toMatch(/(href|src)=["'][^"']+\.(pdf|docx)["']/i); expect(t, f).not.toMatch(/url\([^)]+\.(pdf|docx)\)/i); }
    expect(fs.existsSync(path.join(ROOT, 'features/brand/Athar_Brand_Guidelines_FINAL.pdf'))).toBe(false);
    const cl = read('CHANGELOG.md'), rn = read('RELEASE_NOTES.md'); expect(cl).toContain('## v' + V); expect(rn).toContain('v' + V); expect(fs.existsSync(path.join(ROOT, 'asset-ledger-v' + V + '.csv'))).toBe(true); expect(read('features/brand/README.md')).toContain('PENDING BRAND PACK');
    write('release-metadata', [{ version: V, stamps: stamps.length, assets: rows, narration: nar, palette: PALETTE, tokens: { light: TOK.light.length, dark: TOK.dark.length }, distFiles: files.length }]);
  });

  for (const lang of ['en', 'ar']) for (const [n, id, k] of SLIDES) test(`slide ${n} ${id} ${lang.toUpperCase()} (cache disabled): active, counter ${n} of 48, ${k === 1 ? 'brand fonts loaded or fallback note' : k === 2 ? 'palette HEX == tokens, lockups, clear space, misuse, pack' : '10 tiles with source pills'}; screenshot`, async ({ page }, info) => {
    test.setTimeout(240000); const mobile = info.project.name === 'phone';
    const cdp = await page.context().newCDPSession(page); await cdp.send('Network.enable'); await cdp.send('Network.setCacheDisabled', { cacheDisabled: true }); await setup(page, lang); await open(page, n, lang); await page.waitForTimeout(1200);
    const r = await page.evaluate(async ({ id, n }) => { const sec = document.getElementById(id); const q = (s) => sec.querySelector(s); const qa = (s) => [...sec.querySelectorAll(s)];
      let fonts = null; try { if (document.fonts && document.fonts.ready) { await document.fonts.ready; fonts = [['Cormorant Garamond', 300, 'normal'], ['Cormorant Garamond', 400, 'normal'], ['Cormorant Garamond', 300, 'italic'], ['IBM Plex Mono', 400, 'normal'], ['IBM Plex Sans Arabic', 300, 'normal']].map((f) => ({ family: f[0], weight: f[1], style: f[2], ok: document.fonts.check((f[2] === 'italic' ? 'italic ' : '') + f[1] + ' 16px "' + f[0] + '"') })); } } catch (e) {}
      const imgs = qa('img'); const broken = imgs.filter((i) => i.complete && i.naturalWidth === 0).map((i) => i.getAttribute('src'));
      return { active: sec.classList.contains('is-active'), dataN: sec.getAttribute('data-n'), slideId: sec.getAttribute('data-slide-id'), visibleN: window.__qaVisible().n, aria: sec.getAttribute('aria-label'), dir: document.documentElement.dir, lang: document.documentElement.lang, hash: location.hash,
        counter: (document.querySelector('footer.pagefooter .counter') || {}).textContent, badge: (document.querySelector('[data-testid="deck-version"]') || {}).textContent, html: document.documentElement.getAttribute('data-deck-version'),
        total: window.AtharBrand && window.AtharBrand.total(), first: window.AtharBrand && window.AtharBrand.first(), execTotal: window.AtharExecTeam && window.AtharExecTeam.total, itTotal: window.AtharImpactTiers && window.AtharImpactTiers.total, current: window.AtharImpactTiers && window.AtharImpactTiers.current(),
        fontsAttr: sec.getAttribute('data-fonts'), fontsState: (q('[data-testid="brand-fonts-state"]') || {}).textContent || null, fontsBox: (q('[data-testid="brand-fonts"]') || {}).getAttribute ? q('[data-testid="brand-fonts"]').getAttribute('data-fonts') : null, fonts,
        specimenRows: qa('.br-spec-row').length, specimenAr: qa('.br-spec--ar').length, specimenEn: qa('.br-spec--en').length, systemRows: qa('[data-testid="brand-type-system"] tr').length, scaleRows: qa('[data-testid="brand-type-scale"] tr').length, dos: qa('.br-do li').length, donts: qa('.br-dont li').length,
        swatches: qa('[data-testid="brand-swatch"]').map((s) => s.getAttribute('data-hex')), swatchText: qa('[data-testid="brand-swatch-hex"]').map((c) => c.textContent), swatchBg: qa('.br-swatch-chip').map((c) => getComputedStyle(c).backgroundColor), tokensLight: qa('.br-token-list[data-mode="light"] .br-token').map((li) => li.querySelector('.br-token-k').textContent + ' ' + li.querySelector('.br-token-v').textContent), tokensDark: qa('.br-token-list[data-mode="dark"] .br-token').length,
        lockups: qa('[data-testid^="brand-lockup-"]').map((f) => f.getAttribute('data-testid').replace('brand-lockup-', '') + ':' + (f.querySelector('.br-pill') || {}).getAttribute('data-label')), clear: !!q('[data-testid="brand-clear-space"]'), clearX: q('[data-testid="brand-clear-space"] .br-clear-box') ? q('[data-testid="brand-clear-space"] .br-clear-box').style.getPropertyValue('--br-x') : null, minRows: qa('[data-testid="brand-min-sizes"] tr').length, misuse: qa('[data-testid="brand-misuse"] .br-mis').length, mood: qa('[data-testid="brand-mood"] img').length, pack: (q('[data-testid="brand-pack"]') || {}).textContent, bars: qa('[data-testid="brand-manifest-counts"] .br-bar').length, pending: qa('[data-testid="brand-pending"] li').length, superseded: (q('[data-testid="brand-superseded"]') || {}).textContent,
        tiles: qa('[data-testid="brand-product-tile"]').map((t) => t.getAttribute('data-asset') + ':' + (t.querySelector('.br-pill') || {}).getAttribute('data-label')), tileImgs: qa('[data-testid="brand-product-tile"] img').length,
        imgs: imgs.length, broken, overflowX: sec.scrollWidth > sec.clientWidth + 2, clipId: window.AtharGuide && window.AtharGuide.clipFor ? window.AtharGuide.clipFor(id) : null, railOrder: [...document.querySelectorAll('nav.rail ol li')].map((li) => (li.querySelector('.rail-n') || {}).textContent).join(','), railCurrent: (document.querySelector('nav.rail li.is-current .rail-n') || {}).textContent, nextDisabled: document.querySelector('button.arrow.next').disabled, h2: (q('.s-head h2') || {}).textContent, kicker: (q('.s-kicker') || {}).textContent }; }, { id, n });
    await page.screenshot({ path: path.join(SHOTS, `${PREFIX}-slide-${n}-${lang}-${vp(info)}.png`) });
    let lightbox = null; if (k === 3) { await page.click('[data-testid="brand-product-tile"][data-asset="render-reception-kiosk"]'); await page.waitForSelector('[data-testid="brand-lightbox"][open]', { timeout: 8000 }); lightbox = await page.evaluate(() => { const d = document.querySelector('[data-testid="brand-lightbox"]'); return { open: d.open, img: (d.querySelector('img') || {}).getAttribute('src'), label: (d.querySelector('.br-pill') || {}).getAttribute('data-label') }; }); await page.keyboard.press('Escape'); await page.waitForTimeout(300); lightbox.closed = await page.evaluate(() => !document.querySelector('[data-testid="brand-lightbox"]').open); }
    let tiles = null; if (k === 3) { await page.click('[data-testid="overview-toggle"]'); await page.waitForSelector('[data-testid="overview"] button.ov-card[data-brand]', { timeout: 10000 }); await page.waitForTimeout(500); tiles = await page.evaluate(() => ({ brand: [...document.querySelectorAll('[data-testid="overview"] button.ov-card[data-brand]')].map((b) => b.textContent.trim()), exec: [...document.querySelectorAll('[data-testid="overview"] button.ov-card[data-exec]')].map((b) => b.textContent.trim()), total: document.querySelectorAll('[data-testid="overview"] button.ov-card').length, on: (document.querySelector('[data-testid="overview"] button.ov-card.on') || {}).textContent })); await page.evaluate(() => { const b = document.querySelector('[data-testid="overview"] button.ov-card[data-exec="1"]'); if (b) b.scrollIntoView({ block: 'center' }); }); await page.waitForTimeout(300); await page.screenshot({ path: path.join(SHOTS, `${PREFIX}-section09-10-overview-${lang}-${vp(info)}.png`) }); }
    write(`slide-${n}-${lang}-` + info.project.name, [{ ...r, lightbox, tiles, errors: page.__errors, failedRequests: page.__net }]);
    expect(r.active).toBe(true); expect(r.dataN).toBe(String(n)); expect(r.slideId).toBe(id); expect(r.visibleN).toBe(n); expect(r.lang).toBe(lang); expect(r.dir).toBe(lang === 'ar' ? 'rtl' : 'ltr'); expect(r.hash).toBe('#/28/brand-' + k);
    expect(r.counter).toContain(String(n)); expect(r.counter).toContain('48'); expect(r.badge).toBe('v' + V); expect(r.html).toBe(V); expect(r.total).toBe(48); expect(r.first).toBe(46); expect(r.execTotal).toBe(48); expect(r.itTotal).toBe(48); expect(r.current).toBe(n);
    expect(r.railOrder).toBe('01,02,03,04,05,06,07,08,09,10'); expect(r.railCurrent).toBe('10'); expect(r.h2 && r.h2.length).toBeGreaterThan(3); expect(r.kicker).toContain('10'); expect(r.broken).toEqual([]); expect(r.imgs).toBeGreaterThan(k === 1 ? 0 : 8); expect(r.overflowX).toBe(false);
    expect(r.clipId).toBe('NAR-s' + (46 + k) + (lang === 'ar' ? '-ar' : '')); expect(r.nextDisabled).toBe(k === 3);
    if (k === 1) { expect(['loaded', 'fallback']).toContain(r.fontsAttr); if (r.fontsAttr === 'loaded') { expect(r.fonts.every((f) => f.ok), JSON.stringify(r.fonts)).toBe(true); expect(r.fontsState).toContain('5/5'); } else { expect(r.fontsState).toContain('PENDING BRAND PACK'); } expect(r.specimenRows).toBeGreaterThanOrEqual(5); expect(r.specimenAr).toBeGreaterThanOrEqual(4); expect(r.specimenEn).toBeGreaterThanOrEqual(4); expect(r.systemRows).toBe(6); expect(r.scaleRows).toBe(8); expect(r.dos).toBeGreaterThanOrEqual(3); expect(r.donts).toBeGreaterThanOrEqual(3); }
    if (k === 2) { expect(r.swatches).toEqual(PALETTE); expect(r.swatchText).toEqual(PALETTE); const rgb = (h) => 'rgb(' + [1, 3, 5].map((i) => parseInt(h.slice(i, i + 2), 16)).join(', ') + ')'; expect(r.swatchBg).toEqual(PALETTE.map(rgb)); expect(r.tokensLight).toEqual(TOK.light.map((t) => t.token + ' ' + t.hex)); expect(r.tokensDark).toBe(TOK.dark.length);
      expect(r.lockups).toEqual(['athar-logo-horizontal-primary-1600:OFFICIAL', 'athar-logo-horizontal-reversed:DERIVED FROM OFFICIAL LOGO', 'athar-logo-horizontal-ivory:DERIVED FROM OFFICIAL LOGO', 'athar-logo-horizontal-mono-black:DERIVED FROM OFFICIAL LOGO', 'athar-monogram-deep-ocean:DERIVED FROM OFFICIAL LOGO']); expect(r.clear).toBe(true); expect(r.clearX).toContain('%'); expect(r.minRows).toBe(5); expect(r.misuse).toBe(6); expect(r.mood).toBe(3); expect(r.bars).toBeGreaterThanOrEqual(6); expect(r.pending).toBeGreaterThanOrEqual(3);
      expect(r.pack).toContain('Athar_Brand_Asset_Pack_v3'); expect(r.pack).toContain('Google Drive / SharePoint'); expect(r.pack).toContain('96'); expect(r.pack).toContain('PENDING BRAND PACK'); for (const s of TOK.superseded) expect(r.superseded).toContain(s.hex); }
    if (k === 3) { expect(r.tiles).toHaveLength(10); expect(r.tiles.filter((t) => t.endsWith(':PACK ASSET'))).toHaveLength(5); expect(r.tiles.filter((t) => t.endsWith(':FILM STILL'))).toHaveLength(1); expect(r.tiles.filter((t) => /CONCEPT RENDER/.test(t))).toHaveLength(4); expect(r.tileImgs).toBeGreaterThanOrEqual(12); expect(lightbox.open).toBe(true); expect(lightbox.img).toContain('/assets/brand/product/render-reception-kiosk.'); expect(lightbox.closed).toBe(true);
      expect(tiles.total).toBe(48); expect(tiles.brand.map((t) => t.slice(0, 2))).toEqual(['46', '47', '48']); expect(tiles.exec.map((t) => t.slice(0, 2))).toEqual(['40', '41', '42', '43', '44', '45']); expect(tiles.on).toMatch(/^48/); }
    expect(page.__errors).toEqual([]); expect(page.__net).toEqual([]);
  });

  test('served: 25 hashed brand files 200 + sha256 + immutable; brand-data.js / brand-fonts.css / brand-section.js / build-info.json no-store; build-info commit == deployed HEAD; guideline file names 404', async ({ page }) => {
    test.setTimeout(300000); const rows = [];
    for (const it of ASSETS.items) { const r = await page.request.get(BASE + ASSETS.distBase + it.file + cb(), { headers: NO_CACHE, timeout: 120000 }); const body = await r.body(); const cc = r.headers()['cache-control'] || ''; rows.push({ id: it.id, url: ASSETS.distBase + it.file, status: r.status(), bytes: body.length, sha256: sha256(body), cacheControl: cc, contentType: r.headers()['content-type'] }); expect(r.status(), it.file).toBe(200); expect(sha256(body), it.file).toBe(it.sha256); expect(cc, it.file).toContain('immutable'); }
    const noStore = [];
    for (const p of ['/js/brand-data.js', '/js/brand-section.js', '/assets/brand-fonts.css', '/assets/brand-section.css', '/build-info.json', '/narration/slide-narration.json', '/index.html']) { const r = await page.request.get(BASE + p + cb(), { headers: NO_CACHE }); const cc = r.headers()['cache-control'] || ''; noStore.push({ url: p, status: r.status(), cacheControl: cc }); expect(r.status(), p).toBe(200); expect(cc, p).toBe('no-store'); }
    const info = await (await page.request.get(BASE + '/build-info.json' + cb(), { headers: NO_CACHE })).json(); expect(info.version).toBe(V); expect((info.commit || '').toLowerCase()).toBe(EXPECT_COMMIT);
    const served = await (await page.request.get(BASE + '/js/brand-data.js' + cb(), { headers: NO_CACHE })).text(); const data = JSON.parse(served.replace(/^[\s\S]*?window\.AtharBrandData = /, '').replace(/;\s*$/, '')); expect(data.tokens.palette.map((p) => p.hex)).toEqual(PALETTE); expect(data.version).toBe(V);
    const forbidden = []; for (const name of GUIDE_NAMES) for (const dir of ['/', '/assets/brand/', '/assets/', '/features/brand/', '/brand/']) { const r = await page.request.get(BASE + dir + name + cb(), { headers: NO_CACHE }); forbidden.push({ url: dir + name, status: r.status() }); expect(r.status(), dir + name).toBe(404); }
    for (const p of ['/features/brand/brand-tokens.json', '/features/brand/assets.json', '/features/brand/brand-asset-manifest.csv']) { const r = await page.request.get(BASE + p + cb(), { headers: NO_CACHE }); expect(r.status(), p).toBe(404); }
    const html = await (await page.request.get(BASE + '/index.html' + cb(), { headers: NO_CACHE })).text(); const stamps = [...html.matchAll(/\?v=([0-9.]+)/g)].map((m) => m[1]); expect(stamps.length).toBeGreaterThanOrEqual(28); expect([...new Set(stamps)]).toEqual([V]);
    for (const e of TABLE.slides.filter((s) => s.n >= 46)) for (const f of [e.file, e.ar.file]) { const r = await page.request.get(BASE + f + cb(), { headers: NO_CACHE }); const body = await r.body(); expect(r.status(), f).toBe(200); expect(sha256(body), f).toBe(f === e.file ? e.sha256 : e.ar.sha256); }
    write('served-' + test.info().project.name, [{ files: rows, noStore, forbidden, servedCommit: info.commit, servedVersion: info.version, builtAt: info.builtAt, stamps: stamps.length }]);
  });

  test('deep links 32, 38, 39–45 unchanged + 46–48 (EN + AR); all 48 slides EN + AR with 0 console errors / 0 failed requests; keyboard 45 → 46 → 45; RTL in AR', async ({ page }) => {
    test.setTimeout(360000); await setup(page, 'en'); await open(page, 1); const dirs = {};
    for (const lang of ['en', 'ar']) { if (lang === 'ar') { await page.click('[data-testid="lang-toggle"]'); await page.waitForFunction(() => document.documentElement.dir === 'rtl', null, { timeout: 8000 }); } for (let n = 1; n <= 48; n++) { await page.evaluate((h) => { location.hash = h; }, hashFor(n)); await page.waitForFunction((n) => window.__qaVisible().n === n, n, { timeout: 9000 }); } dirs[lang] = await page.evaluate(() => document.documentElement.dir); }
    const deep = [];
    for (const lang of ['en', 'ar']) for (const n of [32, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48]) { const ctx = await page.context().browser().newContext({ viewport: page.viewportSize() }); const p2 = await ctx.newPage(); await setup(p2, lang); await p2.goto(BASE + '/?lang=' + lang + hashFor(n), { waitUntil: 'load' }); await p2.waitForFunction(() => !!window.AtharGuide, null, { timeout: 20000 }); await p2.waitForFunction((n) => window.__qaVisible().n === n, n, { timeout: 15000 }); const v = await p2.evaluate(() => ({ ...window.__qaVisible(), dir: document.documentElement.dir, hash: location.hash })); deep.push({ lang, n, ...v, errors: p2.__errors, failed: p2.__net }); expect(v.n, lang + ' ' + n).toBe(n); expect(v.hash, lang + ' ' + n).toBe(hashFor(n)); expect(v.dir).toBe(lang === 'ar' ? 'rtl' : 'ltr'); expect(p2.__errors).toEqual([]); expect(p2.__net).toEqual([]); await ctx.close(); }
    /* keyboard hand-over at the section boundary (EN deck) */
    const ctx = await page.context().browser().newContext({ viewport: page.viewportSize() }); const p3 = await ctx.newPage(); await setup(p3, 'en'); await open(p3, 45, 'en'); await p3.waitForTimeout(500);
    await p3.keyboard.press('ArrowRight'); await p3.waitForFunction(() => window.__qaVisible().n === 46, null, { timeout: 8000 }); const k1 = await p3.evaluate(() => ({ ...window.__qaVisible(), hash: location.hash, counter: document.querySelector('footer.pagefooter .counter').textContent }));
    await p3.keyboard.press('ArrowLeft'); await p3.waitForFunction(() => window.__qaVisible().n === 45, null, { timeout: 8000 }); const k2 = await p3.evaluate(() => ({ ...window.__qaVisible(), hash: location.hash }));
    await p3.keyboard.press('End'); await p3.waitForTimeout(600); const k3 = await p3.evaluate(() => ({ ...window.__qaVisible(), hash: location.hash, nextDisabled: document.querySelector('button.arrow.next').disabled }));
    write('sweep-' + test.info().project.name, [{ dirs, errors: page.__errors, failedRequests: page.__net, deep, keys: { k1, k2, k3 } }]);
    expect(dirs).toEqual({ en: 'ltr', ar: 'rtl' }); expect(page.__errors).toEqual([]); expect(page.__net).toEqual([]); expect(k1.slideId).toBe('s-brand-typography'); expect(k1.hash).toBe('#/28/brand-1'); expect(k1.counter).toContain('46'); expect(k2.slideId).toBe('s-exec-lorenzo'); expect(k2.hash).toBe('#/28/exec-6'); expect(p3.__errors).toEqual([]); await ctx.close();
  });
});
